.\" man page 8/2/2015 vbextreme 
.\" source www.github.vbextreme/easyframework
.\"

.TH man 3 "08 March 2015" "1.0" "easyframework man page"

.SH NAME
Easy Framework

.SH DESCRIPTION
Easy framework is a set of libraries for the C language.
EF contains numerous functions for general use, each function group is identified by three letters followed by an underscore,
 achieving a kind of namescpace on it, a subgroup Toggle and finally the name of the function.
For example, the library EasyConsole than letting of interaggire with the terminal will have its namespace called "Con_" and 
to clear the screen just type "con_cls ()"

.SH EXTENDED DESCRIPTION
Library:
.br
 1\. easytype: contains all types used in the framework
.br
 2\. eayalloc: memory management
.br
 3\. easybenchmark: stopwatch
.br
 4\. easyconsole: iteration with the terminal
.br
 5\. easycrypto: encrypts and decrypts
.br
 6\. easyfile: file and directory management
.br
 7\. easylist: linked lists, stacks, queues
.br
 8\. easymath: mathematics, fft, matrix calculations, dates, etc
.br
 9\. easyopt: simplifying the use of opt
.br
10\. easyprocess: simplifying the use of processes and information / proc filesystem including process info, net info and much more
.br
11\. easyserial: rs232 communication
.br
12\. easysocket: tcp ipv4 server client communication
.br
13\. easystring: many functions for working with strings including regular expressions
.br
14\. easythread: many function for working with thread and synchronizations
.br

.SH SYNOPSIS
#include <easytype\.h>
.br
#include <eayalloc\.h>
.br
#include <easybenchmark\.h>
.br
#include <easyconsole\.h>
.br
#include <easycrypto\.h>
.br
#include <easyfile\.h>
.br
#include <easylist\.h>
.br
#include <easymath\.h>
.br
#include <easyopt\.h>
.br
#include <easyprocess\.h>
.br
#include <easyserial\.h>
.br
#include <easysocket\.h>
.br
#include <easystring\.h>
.br
#include <easythread\.h>

.SH NOTES
.br
easytype is only a header not need link with -leasytype
.br
for make -leasyconsole -leasycripto , etc

.SH SEE ALSO
easytype(3) easyalloc(3) easybenchmark(3) easyconsole(3) easycrypto(3) easyfile(3) easylist(3) easymath(3) easyopt(3)
easyprocess(3) easyserial(3) easysocket(3) easystring(3) easythread(3)

.SH LICENSE
gpl

.SH AUTHORS
vbextreme

