#!/bin/bash


#Order
elst="easyalloc easybenchmark easyconsole easycrypto easyfile easylist easymath easyserial easystring"
elst="$elst easythread easyopt easymarklang easysocket easyprocess easyhttp"

echo "--------------------------"
echo "- Install Easy Framework -"
echo "--------------------------"
echo ""

./easystatus easytype
cp ./easytype/easytype.h /usr/include/easytype.h
./easystatus -o

for e in ${elst[@]}; do
	cd "./$e"
	make -f ./makefile.auto libinstall
	if [[ $? != 0 ]]; then
		cd ..
		out="$e report error on https://github.com/vbextreme/EasyFramework/issues"
		./easystatus $out
		./easystatus -e
		exit 1
	fi
	cd ..
	./easystatus "$e"
	./easystatus -o
done


echo "------------"
echo "- Complete -"
echo "------------"
echo ""
