#!/bin/bash


#Order
elst="easyalloc easybenchmark easyconsole easycrypto easyfile easylist easymath easyserial easystring"
elst="$elst easythread easyopt easymarklang easysocket easyprocess easyhttp"

echo "--------------------------"
echo "- Uinstall Easy Framework -"
echo "--------------------------"
echo ""

./easystatus easytype
rm -f /usr/include/easytype.h
./easystatus -o

for e in ${elst[@]}; do
	cd "./$e"
	make -f ./makefile.auto libuninstall
	cd ..
	./easystatus "$e"
	./easystatus -o
done


echo "------------"
echo "- Complete -"
echo "------------"
echo ""
