.TH "argdef" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argdef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <optex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBhasset\fP"
.br
.ti -1c
.RI "int \fBvshort\fP"
.br
.ti -1c
.RI "char * \fBvlong\fP"
.br
.ti -1c
.RI "\fBargdef_e\fP \fBtypeParam\fP"
.br
.ti -1c
.RI "void * \fBautoset\fP"
.br
.ti -1c
.RI "char * \fBdescript\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file optex\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* argdef::autoset"
automatic assign value 
.PP
Definition at line 19 of file optex\&.h\&.
.SS "char* argdef::descript"
descript of argument 
.PP
Definition at line 20 of file optex\&.h\&.
.SS "int argdef::hasset"
argument is setting 
.PP
Definition at line 15 of file optex\&.h\&.
.SS "\fBargdef_e\fP argdef::typeParam"

.PP
\fBSee also\fP
.RS 4
\fBargdef_e\fP 
.RE
.PP

.PP
Definition at line 18 of file optex\&.h\&.
.SS "char* argdef::vlong"
long format value 
.PP
Definition at line 17 of file optex\&.h\&.
.SS "int argdef::vshort"
short format value 
.PP
Definition at line 16 of file optex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
