.TH "deadpoll" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deadpoll
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deadpoll\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpollEvent_s\fP * \fBevents\fP"
.br
.ti -1c
.RI "int \fBpollfd\fP"
.br
.ti -1c
.RI "size_t \fBnevents\fP"
.br
.ti -1c
.RI "\fBpollCbk_f\fP \fBtimeout\fP"
.br
.ti -1c
.RI "void * \fBtimeoutarg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file deadpoll\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBpollEvent_s\fP* deadpoll::events"

.PP
Definition at line 32 of file deadpoll\&.h\&.
.SS "size_t deadpoll::nevents"

.PP
Definition at line 34 of file deadpoll\&.h\&.
.SS "int deadpoll::pollfd"

.PP
Definition at line 33 of file deadpoll\&.h\&.
.SS "\fBpollCbk_f\fP deadpoll::timeout"

.PP
Definition at line 35 of file deadpoll\&.h\&.
.SS "void* deadpoll::timeoutarg"

.PP
Definition at line 36 of file deadpoll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
