.TH "eerr" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eerr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <err\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdescript\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBflags\fP"
.br
.ti -1c
.RI "size_t * \fBrestore\fP"
.br
.ti -1c
.RI "size_t \fBrc\fP"
.br
.ti -1c
.RI "size_t \fBrsz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file err\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* eerr::descript"

.PP
Definition at line 8 of file err\&.h\&.
.SS "size_t eerr::flags"

.PP
Definition at line 11 of file err\&.h\&.
.SS "size_t eerr::len"

.PP
Definition at line 10 of file err\&.h\&.
.SS "size_t eerr::rc"

.PP
Definition at line 13 of file err\&.h\&.
.SS "size_t* eerr::restore"

.PP
Definition at line 12 of file err\&.h\&.
.SS "size_t eerr::rsz"

.PP
Definition at line 14 of file err\&.h\&.
.SS "size_t eerr::size"

.PP
Definition at line 9 of file err\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
