.TH "event" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threads\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfutex\fP"
.br
.ti -1c
.RI "int \fBprivate\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 131 of file threads\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int event::fd"

.PP
Definition at line 134 of file threads\&.h\&.
.SS "int event::futex"

.PP
Definition at line 132 of file threads\&.h\&.
.SS "int event::private"

.PP
Definition at line 133 of file threads\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
