.TH "esport" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esport
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file socket\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char* esport::name"

.PP
Definition at line 36 of file socket\&.h\&.
.SS "int esport::port"

.PP
Definition at line 37 of file socket\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
