.TH "esunix" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esunix
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct ucred \fBcredentials\fP"
.br
.ti -1c
.RI "struct sockaddr_un \fBaddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file socket\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct sockaddr_un esunix::addr"

.PP
Definition at line 56 of file socket\&.h\&.
.SS "struct ucred esunix::credentials"

.PP
Definition at line 55 of file socket\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
