.TH "ftp" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ftp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBwww_s\fP \fBwww\fP"
.br
.ti -1c
.RI "char * \fBsite\fP"
.br
.ti -1c
.RI "size_t \fBlenSite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file ftp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t ftp::lenSite"

.PP
Definition at line 23 of file ftp\&.h\&.
.SS "char* ftp::site"

.PP
Definition at line 22 of file ftp\&.h\&.
.SS "\fBwww_s\fP ftp::www"

.PP
Definition at line 21 of file ftp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
