.TH "ftRender" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftRender
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf_t\fP \fButf\fP"
.br
.ti -1c
.RI "\fBg2dImage_s\fP * \fBimg\fP"
.br
.ti -1c
.RI "unsigned \fBwidth\fP"
.br
.ti -1c
.RI "unsigned \fBheight\fP"
.br
.ti -1c
.RI "unsigned \fBpitch\fP"
.br
.ti -1c
.RI "unsigned \fBhoriAdvance\fP"
.br
.ti -1c
.RI "int \fBhoriBearingX\fP"
.br
.ti -1c
.RI "int \fBhoriBearingY\fP"
.br
.ti -1c
.RI "unsigned \fBlinearHoriAdvance\fP"
.br
.ti -1c
.RI "unsigned \fBvertAdvance\fP"
.br
.ti -1c
.RI "unsigned \fBvertBearingX\fP"
.br
.ti -1c
.RI "unsigned \fBvertBearingY\fP"
.br
.ti -1c
.RI "unsigned \fBlinearVertAdvance\fP"
.br
.ti -1c
.RI "long \fBdescender\fP"
.br
.ti -1c
.RI "int \fBpenAdvance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file ft\&.h\&.
.SH "Field Documentation"
.PP 
.SS "long ftRender::descender"

.PP
Definition at line 29 of file ft\&.h\&.
.SS "unsigned ftRender::height"

.PP
Definition at line 19 of file ft\&.h\&.
.SS "unsigned ftRender::horiAdvance"

.PP
Definition at line 21 of file ft\&.h\&.
.SS "int ftRender::horiBearingX"

.PP
Definition at line 22 of file ft\&.h\&.
.SS "int ftRender::horiBearingY"

.PP
Definition at line 23 of file ft\&.h\&.
.SS "\fBg2dImage_s\fP* ftRender::img"

.PP
Definition at line 17 of file ft\&.h\&.
.SS "unsigned ftRender::linearHoriAdvance"

.PP
Definition at line 24 of file ft\&.h\&.
.SS "unsigned ftRender::linearVertAdvance"

.PP
Definition at line 28 of file ft\&.h\&.
.SS "int ftRender::penAdvance"

.PP
Definition at line 30 of file ft\&.h\&.
.SS "unsigned ftRender::pitch"

.PP
Definition at line 20 of file ft\&.h\&.
.SS "\fButf_t\fP ftRender::utf"

.PP
Definition at line 16 of file ft\&.h\&.
.SS "unsigned ftRender::vertAdvance"

.PP
Definition at line 25 of file ft\&.h\&.
.SS "unsigned ftRender::vertBearingX"

.PP
Definition at line 26 of file ft\&.h\&.
.SS "unsigned ftRender::vertBearingY"

.PP
Definition at line 27 of file ft\&.h\&.
.SS "unsigned ftRender::width"

.PP
Definition at line 18 of file ft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
