.TH "fzsElement" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fzsElement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fzs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBstr\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBdistance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure to use in vector for fzs qsort 
.PP
Definition at line 8 of file fzs\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t fzsElement::distance"
laste distance calcolate 
.PP
Definition at line 11 of file fzs\&.h\&.
.SS "size_t fzsElement::len"
len of string 
.PP
Definition at line 10 of file fzs\&.h\&.
.SS "const char* fzsElement::str"
pointer to string 
.PP
Definition at line 9 of file fzs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
