.TH "filetmp" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filetmp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <file\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [PATH_MAX]"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file file\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int filetmp::fd"

.PP
Definition at line 26 of file file\&.h\&.
.SS "char filetmp::name[PATH_MAX]"
tmp file name 
.PP
Definition at line 25 of file file\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
