.TH "ftUtfCustom" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftUtfCustom
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf_t\fP \fButf\fP"
.br
.ti -1c
.RI "\fBftUtfCustom_f\fP \fBfn\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file ft\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBftUtfCustom_f\fP ftUtfCustom::fn"

.PP
Definition at line 54 of file ft\&.h\&.
.SS "void* ftUtfCustom::userdata"

.PP
Definition at line 55 of file ft\&.h\&.
.SS "\fButf_t\fP ftUtfCustom::utf"

.PP
Definition at line 53 of file ft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
