.TH "ftFont" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftFont
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBfname\fP"
.br
.ti -1c
.RI "char \fBname\fP [\fBFT_FONT_NAME_SIZE\fP]"
.br
.ti -1c
.RI "FT_Face \fBface\fP"
.br
.ti -1c
.RI "unsigned long \fBwidth\fP"
.br
.ti -1c
.RI "unsigned long \fBheight\fP"
.br
.ti -1c
.RI "long \fBdescender\fP"
.br
.ti -1c
.RI "long \fBascender\fP"
.br
.ti -1c
.RI "long \fBadvanceX\fP"
.br
.ti -1c
.RI "long \fBadvanceY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file ft\&.h\&.
.SH "Field Documentation"
.PP 
.SS "long ftFont::advanceX"

.PP
Definition at line 41 of file ft\&.h\&.
.SS "long ftFont::advanceY"

.PP
Definition at line 42 of file ft\&.h\&.
.SS "long ftFont::ascender"

.PP
Definition at line 40 of file ft\&.h\&.
.SS "long ftFont::descender"

.PP
Definition at line 39 of file ft\&.h\&.
.SS "FT_Face ftFont::face"

.PP
Definition at line 36 of file ft\&.h\&.
.SS "const char* ftFont::fname"

.PP
Definition at line 34 of file ft\&.h\&.
.SS "unsigned long ftFont::height"

.PP
Definition at line 38 of file ft\&.h\&.
.SS "char ftFont::name[\fBFT_FONT_NAME_SIZE\fP]"

.PP
Definition at line 35 of file ft\&.h\&.
.SS "unsigned long ftFont::width"

.PP
Definition at line 37 of file ft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
