.TH "ftFonts" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftFonts
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBftFont_s\fP * \fBfont\fP"
.br
.ti -1c
.RI "\fBrbhash_s\fP * \fBcharmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file ft\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBrbhash_s\fP* ftFonts::charmap"

.PP
Definition at line 47 of file ft\&.h\&.
.SS "\fBftFont_s\fP* ftFonts::font"
first is font, sucessive is fallback 
.PP
Definition at line 46 of file ft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
