.TH "ftpStat" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftpStat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ftp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBlink\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "time_t \fBtime\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ftp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* ftpStat::link"

.PP
Definition at line 14 of file ftp\&.h\&.
.SS "int ftpStat::mode"

.PP
Definition at line 17 of file ftp\&.h\&.
.SS "char* ftpStat::name"

.PP
Definition at line 13 of file ftp\&.h\&.
.SS "size_t ftpStat::size"

.PP
Definition at line 15 of file ftp\&.h\&.
.SS "time_t ftpStat::time"

.PP
Definition at line 16 of file ftp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
