.TH "guiText" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiText
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiText\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBguiLayer_s\fP * \fBrender\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBscroll\fP"
.br
.ti -1c
.RI "\fBg2dCoord_s\fP \fBcursor\fP"
.br
.ti -1c
.RI "int \fBcursorOffsetX\fP"
.br
.ti -1c
.RI "int \fBcursorOffsetY\fP"
.br
.ti -1c
.RI "\fBguiTimer_s\fP * \fBblink\fP"
.br
.ti -1c
.RI "unsigned \fBblinktime\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBtext\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBresize\fP"
.br
.ti -1c
.RI "\fButf8Iterator_s\fP \fBit\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBselStart\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBselEnd\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBclipmem\fP"
.br
.ti -1c
.RI "\fBftFonts_s\fP * \fBfonts\fP"
.br
.ti -1c
.RI "\fBg2dColor_t\fP \fBforeground\fP"
.br
.ti -1c
.RI "\fBg2dColor_t\fP \fBselect\fP"
.br
.ti -1c
.RI "\fBg2dColor_t\fP \fBcolCursor\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "unsigned \fBtabspace\fP"
.br
.ti -1c
.RI "unsigned \fBspacesize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file guiText\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBguiTimer_s\fP* guiText::blink"

.PP
Definition at line 42 of file guiText\&.h\&.
.SS "unsigned guiText::blinktime"

.PP
Definition at line 43 of file guiText\&.h\&.
.SS "\fButf8_t\fP* guiText::clipmem"

.PP
Definition at line 52 of file guiText\&.h\&.
.SS "\fBg2dColor_t\fP guiText::colCursor"

.PP
Definition at line 57 of file guiText\&.h\&.
.SS "\fBg2dCoord_s\fP guiText::cursor"

.PP
Definition at line 39 of file guiText\&.h\&.
.SS "int guiText::cursorOffsetX"

.PP
Definition at line 40 of file guiText\&.h\&.
.SS "int guiText::cursorOffsetY"

.PP
Definition at line 41 of file guiText\&.h\&.
.SS "unsigned guiText::flags"

.PP
Definition at line 58 of file guiText\&.h\&.
.SS "\fBftFonts_s\fP* guiText::fonts"

.PP
Definition at line 54 of file guiText\&.h\&.
.SS "\fBg2dColor_t\fP guiText::foreground"

.PP
Definition at line 55 of file guiText\&.h\&.
.SS "\fButf8Iterator_s\fP guiText::it"

.PP
Definition at line 49 of file guiText\&.h\&.
.SS "size_t guiText::len"

.PP
Definition at line 46 of file guiText\&.h\&.
.SS "\fBguiLayer_s\fP* guiText::render"

.PP
Definition at line 37 of file guiText\&.h\&.
.SS "size_t guiText::resize"

.PP
Definition at line 48 of file guiText\&.h\&.
.SS "\fBg2dPoint_s\fP guiText::scroll"

.PP
Definition at line 38 of file guiText\&.h\&.
.SS "\fBg2dColor_t\fP guiText::select"

.PP
Definition at line 56 of file guiText\&.h\&.
.SS "\fButf8_t\fP* guiText::selEnd"

.PP
Definition at line 51 of file guiText\&.h\&.
.SS "\fButf8_t\fP* guiText::selStart"

.PP
Definition at line 50 of file guiText\&.h\&.
.SS "size_t guiText::size"

.PP
Definition at line 47 of file guiText\&.h\&.
.SS "unsigned guiText::spacesize"

.PP
Definition at line 60 of file guiText\&.h\&.
.SS "unsigned guiText::tabspace"

.PP
Definition at line 59 of file guiText\&.h\&.
.SS "\fButf8_t\fP* guiText::text"

.PP
Definition at line 45 of file guiText\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
