.TH "guiDiv" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiDiv
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiDiv\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBguiDivMode_e\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBsep\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBscroll\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBlastElement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file guiDiv\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBg2dPoint_s\fP guiDiv::lastElement"

.PP
Definition at line 17 of file guiDiv\&.h\&.
.SS "\fBguiDivMode_e\fP guiDiv::mode"

.PP
Definition at line 14 of file guiDiv\&.h\&.
.SS "\fBg2dPoint_s\fP guiDiv::scroll"

.PP
Definition at line 16 of file guiDiv\&.h\&.
.SS "\fBg2dPoint_s\fP guiDiv::sep"

.PP
Definition at line 15 of file guiDiv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
