.TH "include/ef/guiText.h" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ef/guiText.h
.SH SYNOPSIS
.br
.PP
\fC#include <ef/gui\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBguiText\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGUI_TEXT_REND_TEXT\fP   0x000001"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_REND_CURSOR\fP   0x000008"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_REND_SCROLL\fP   0x000010"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_REND_CURON\fP   0x000020"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_INSERT\fP   0x000100"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_SCROLL_X\fP   0x000200"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_SCROLL_Y\fP   0x000400"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_CUR_VISIBLE\fP   0x000800"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_SEL\fP   0x001000"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_FLAGS_END\fP   24"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_FLAGS_MASK\fP   0xFFFFFF"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_CURSOR_THIN\fP   (0<<\fBGUI_TEXT_FLAGS_END\fP)"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_CURSOR_LIGHT\fP   (1<<\fBGUI_TEXT_FLAGS_END\fP)"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_CURSOR_PLENTIFUL\fP   (2<<\fBGUI_TEXT_FLAGS_END\fP)"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_CURSOR_FAT\fP   (3<<\fBGUI_TEXT_FLAGS_END\fP)"
.br
.ti -1c
.RI "#define \fBGUI_TEXT_WORD_SEP\fP   ' \\n\\t`~!@#$%^&*()+{}|[]\\\\;':\\'<>?,\&./'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_BLINK\fP   'text\&.cursor\&.blink'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_CURSOR\fP   'text\&.cursor\&.mode'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_CURSOR_COLOR\fP   'text\&.cursor\&.color'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_SEL_COLOR\fP   'text\&.sel\&.color'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_TAB\fP   'text\&.tab'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_FOREGROUND\fP   'text\&.foreground'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_SCROLL_X\fP   'text\&.scroll\&.x'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_TEXT_SCROLL_Y\fP   'text\&.scroll\&.y'"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBguiText\fP \fBguiText_s\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBguiText_s\fP * \fBgui_text_new\fP (\fBftFonts_s\fP *font, \fBg2dColor_t\fP foreground, \fBg2dColor_t\fP select, \fBg2dColor_t\fP colCursor, unsigned tabspace, unsigned blinktime, unsigned flags)"
.br
.ti -1c
.RI "\fBgui_s\fP * \fBgui_text_attach\fP (\fBgui_s\fP *\fBgui\fP, \fBguiText_s\fP *txt)"
.br
.ti -1c
.RI "void \fBgui_text_free\fP (\fBguiText_s\fP *txt)"
.br
.ti -1c
.RI "void \fBgui_text_flags_set\fP (\fBgui_s\fP *\fBgui\fP, unsigned flags)"
.br
.ti -1c
.RI "void \fBgui_text_ir_toggle\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "const \fButf8_t\fP * \fBgui_text_str_raw\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBgui_text_str\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_print\fP (\fBgui_s\fP *\fBgui\fP, const \fButf8_t\fP *text)"
.br
.ti -1c
.RI "void \fBgui_text_sel\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_unsel\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_sel_del\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBgui_text_sel_get\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "size_t \fBgui_text_line_right_len\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "size_t \fBgui_text_line_left_len\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBgui_text_back_line_ptr\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBgui_text_next_line_ptr\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_put\fP (\fBgui_s\fP *\fBgui\fP, \fButf_t\fP utf)"
.br
.ti -1c
.RI "void \fBgui_text_del\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_backspace\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_change\fP (\fBgui_s\fP *\fBgui\fP, unsigned modeflags)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_next\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_prev\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_end\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_home\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_scroll_left\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_scroll_right\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "\fBerr_t\fP \fBgui_text_cursor_up\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "\fBerr_t\fP \fBgui_text_cursor_down\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_pagdn\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_pagup\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_cursor_on_position\fP (\fBgui_s\fP *\fBgui\fP, unsigned x, unsigned y)"
.br
.ti -1c
.RI "void \fBgui_text_render_cursor\fP (\fBgui_s\fP *\fBgui\fP, \fB__unused\fP \fBguiLayer_s\fP **img, \fB__unused\fP void *ud)"
.br
.ti -1c
.RI "void \fBgui_text_render_text\fP (\fBgui_s\fP *\fBgui\fP, int partial)"
.br
.ti -1c
.RI "void \fBgui_text_render_scroll\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_text_redraw\fP (\fBgui_s\fP *\fBgui\fP, int partial)"
.br
.ti -1c
.RI "int \fBgui_text_event_key\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *\fBevent\fP)"
.br
.ti -1c
.RI "int \fBgui_text_event_redraw\fP (\fBgui_s\fP *\fBgui\fP, \fB__unused\fP \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_text_event_clipboard\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_text_event_free\fP (\fBgui_s\fP *\fBgui\fP, \fB__unused\fP \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_text_event_themes\fP (\fB__unused\fP \fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_text_timer_blink\fP (\fBguiTimer_s\fP *timer)"
.br
.ti -1c
.RI "int \fBgui_text_event_focus\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_text_event_mouse\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *\fBevent\fP)"
.br
.ti -1c
.RI "int \fBgui_text_event_move\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *\fBevent\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GUI_TEXT_CUR_VISIBLE   0x000800"

.PP
Definition at line 15 of file guiText\&.h\&.
.SS "#define GUI_TEXT_CURSOR_FAT   (3<<\fBGUI_TEXT_FLAGS_END\fP)"

.PP
Definition at line 24 of file guiText\&.h\&.
.SS "#define GUI_TEXT_CURSOR_LIGHT   (1<<\fBGUI_TEXT_FLAGS_END\fP)"

.PP
Definition at line 22 of file guiText\&.h\&.
.SS "#define GUI_TEXT_CURSOR_PLENTIFUL   (2<<\fBGUI_TEXT_FLAGS_END\fP)"

.PP
Definition at line 23 of file guiText\&.h\&.
.SS "#define GUI_TEXT_CURSOR_THIN   (0<<\fBGUI_TEXT_FLAGS_END\fP)"

.PP
Definition at line 21 of file guiText\&.h\&.
.SS "#define GUI_TEXT_FLAGS_END   24"

.PP
Definition at line 18 of file guiText\&.h\&.
.SS "#define GUI_TEXT_FLAGS_MASK   0xFFFFFF"

.PP
Definition at line 19 of file guiText\&.h\&.
.SS "#define GUI_TEXT_INSERT   0x000100"

.PP
Definition at line 12 of file guiText\&.h\&.
.SS "#define GUI_TEXT_REND_CURON   0x000020"

.PP
Definition at line 10 of file guiText\&.h\&.
.SS "#define GUI_TEXT_REND_CURSOR   0x000008"

.PP
Definition at line 8 of file guiText\&.h\&.
.SS "#define GUI_TEXT_REND_SCROLL   0x000010"

.PP
Definition at line 9 of file guiText\&.h\&.
.SS "#define GUI_TEXT_REND_TEXT   0x000001"

.PP
Definition at line 7 of file guiText\&.h\&.
.SS "#define GUI_TEXT_SCROLL_X   0x000200"

.PP
Definition at line 13 of file guiText\&.h\&.
.SS "#define GUI_TEXT_SCROLL_Y   0x000400"

.PP
Definition at line 14 of file guiText\&.h\&.
.SS "#define GUI_TEXT_SEL   0x001000"

.PP
Definition at line 16 of file guiText\&.h\&.
.SS "#define GUI_TEXT_WORD_SEP   ' \\n\\t`~!@#$%^&*()+{}|[]\\\\;':\\'<>?,\&./'"

.PP
Definition at line 26 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_BLINK   'text\&.cursor\&.blink'"

.PP
Definition at line 28 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_CURSOR   'text\&.cursor\&.mode'"

.PP
Definition at line 29 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_CURSOR_COLOR   'text\&.cursor\&.color'"

.PP
Definition at line 30 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_FOREGROUND   'text\&.foreground'"

.PP
Definition at line 33 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_SCROLL_X   'text\&.scroll\&.x'"

.PP
Definition at line 34 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_SCROLL_Y   'text\&.scroll\&.y'"

.PP
Definition at line 35 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_SEL_COLOR   'text\&.sel\&.color'"

.PP
Definition at line 31 of file guiText\&.h\&.
.SS "#define GUI_THEME_TEXT_TAB   'text\&.tab'"

.PP
Definition at line 32 of file guiText\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBguiText\fP \fBguiText_s\fP"

.SH "Function Documentation"
.PP 
.SS "\fBgui_s\fP* gui_text_attach (\fBgui_s\fP * gui, \fBguiText_s\fP * txt)"
attach text to gui 
.SS "\fButf8_t\fP* gui_text_back_line_ptr (\fBgui_s\fP * gui)"
back one line 
.SS "void gui_text_backspace (\fBgui_s\fP * gui)"
backspace 
.SS "void gui_text_cursor_change (\fBgui_s\fP * gui, unsigned modeflags)"
change type of cursaor 
.SS "\fBerr_t\fP gui_text_cursor_down (\fBgui_s\fP * gui)"
cursor down 
.SS "void gui_text_cursor_end (\fBgui_s\fP * gui)"
cursor to end 
.SS "void gui_text_cursor_home (\fBgui_s\fP * gui)"
cursor to home 
.SS "void gui_text_cursor_next (\fBgui_s\fP * gui)"
cursor next 
.SS "void gui_text_cursor_on_position (\fBgui_s\fP * gui, unsigned x, unsigned y)"
set cursor on coordinate 
.SS "void gui_text_cursor_pagdn (\fBgui_s\fP * gui)"
cursor pag down 
.SS "void gui_text_cursor_pagup (\fBgui_s\fP * gui)"
cursors pagup 
.SS "void gui_text_cursor_prev (\fBgui_s\fP * gui)"
cursor prev 
.SS "void gui_text_cursor_scroll_left (\fBgui_s\fP * gui)"
scroll left 
.SS "void gui_text_cursor_scroll_right (\fBgui_s\fP * gui)"
scroll right 
.SS "\fBerr_t\fP gui_text_cursor_up (\fBgui_s\fP * gui)"
cursor up 
.SS "void gui_text_del (\fBgui_s\fP * gui)"
del char 
.SS "int gui_text_event_clipboard (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * ev)"
event clipboard 
.SS "int gui_text_event_focus (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * ev)"
event focus 
.SS "int gui_text_event_free (\fBgui_s\fP * gui, \fB__unused\fP \fBxorgEvent_s\fP * ev)"
event free 
.SS "int gui_text_event_key (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * event)"
event on key 
.SS "int gui_text_event_mouse (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * event)"
event mouse 
.SS "int gui_text_event_move (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * event)"

.SS "int gui_text_event_redraw (\fBgui_s\fP * gui, \fB__unused\fP \fBxorgEvent_s\fP * ev)"
event redraw 
.SS "int gui_text_event_themes (\fB__unused\fP \fBgui_s\fP * gui, \fBxorgEvent_s\fP * ev)"

.SS "void gui_text_flags_set (\fBgui_s\fP * gui, unsigned flags)"
sets flags 
.SS "void gui_text_free (\fBguiText_s\fP * txt)"
free text 
.SS "void gui_text_ir_toggle (\fBgui_s\fP * gui)"
insert/replace 
.SS "size_t gui_text_line_left_len (\fBgui_s\fP * gui)"
left len 
.SS "size_t gui_text_line_right_len (\fBgui_s\fP * gui)"
right len 
.SS "\fBguiText_s\fP* gui_text_new (\fBftFonts_s\fP * font, \fBg2dColor_t\fP foreground, \fBg2dColor_t\fP select, \fBg2dColor_t\fP colCursor, unsigned tabspace, unsigned blinktime, unsigned flags)"
create new text 
.SS "\fButf8_t\fP* gui_text_next_line_ptr (\fBgui_s\fP * gui)"
next ona line 
.SS "void gui_text_print (\fBgui_s\fP * gui, const \fButf8_t\fP * text)"
write a string 
.SS "void gui_text_put (\fBgui_s\fP * gui, \fButf_t\fP utf)"
put char 
.SS "void gui_text_redraw (\fBgui_s\fP * gui, int partial)"
redraw text 
.SS "void gui_text_render_cursor (\fBgui_s\fP * gui, \fB__unused\fP \fBguiLayer_s\fP ** img, \fB__unused\fP void * ud)"
render cursor 
.SS "void gui_text_render_scroll (\fBgui_s\fP * gui)"
render scroll 
.SS "void gui_text_render_text (\fBgui_s\fP * gui, int partial)"
render text 
.SS "void gui_text_sel (\fBgui_s\fP * gui)"
sel text 
.SS "void gui_text_sel_del (\fBgui_s\fP * gui)"
delete selection 
.SS "\fButf8_t\fP* gui_text_sel_get (\fBgui_s\fP * gui)"
get text selection, remember to free 
.SS "\fButf8_t\fP* gui_text_str (\fBgui_s\fP * gui)"
get text string, remember to free 
.SS "const \fButf8_t\fP* gui_text_str_raw (\fBgui_s\fP * gui)"
get raw str 
.SS "int gui_text_timer_blink (\fBguiTimer_s\fP * timer)"
event timer blink 
.SS "void gui_text_unsel (\fBgui_s\fP * gui)"
unsel text 
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
