.TH "guiLabel" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiLabel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBg2dImage_s\fP * \fBrender\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBscroll\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBtext\fP"
.br
.ti -1c
.RI "\fBftFonts_s\fP * \fBfonts\fP"
.br
.ti -1c
.RI "int \fBautowrap\fP"
.br
.ti -1c
.RI "\fBg2dColor_t\fP \fBforeground\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file guiLabel\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int guiLabel::autowrap"

.PP
Definition at line 16 of file guiLabel\&.h\&.
.SS "unsigned guiLabel::flags"

.PP
Definition at line 12 of file guiLabel\&.h\&.
.SS "\fBftFonts_s\fP* guiLabel::fonts"

.PP
Definition at line 15 of file guiLabel\&.h\&.
.SS "\fBg2dColor_t\fP guiLabel::foreground"

.PP
Definition at line 17 of file guiLabel\&.h\&.
.SS "\fBg2dImage_s\fP* guiLabel::render"

.PP
Definition at line 11 of file guiLabel\&.h\&.
.SS "\fBg2dPoint_s\fP guiLabel::scroll"

.PP
Definition at line 13 of file guiLabel\&.h\&.
.SS "\fButf8_t\fP* guiLabel::text"

.PP
Definition at line 14 of file guiLabel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
