.TH "guiOption" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiOption
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiOptionBox\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBguiCaption_s\fP * \fBcaption\fP"
.br
.ti -1c
.RI "\fBguiComposite_s\fP * \fBstate\fP [\fBGUI_OPTION_STATE_COUNT\fP]"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBparentKey\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file guiOptionBox\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBguiCaption_s\fP* guiOption::caption"

.PP
Definition at line 25 of file guiOptionBox\&.h\&.
.SS "int guiOption::flags"

.PP
Definition at line 28 of file guiOptionBox\&.h\&.
.SS "\fBguiEvent_f\fP guiOption::parentKey"

.PP
Definition at line 27 of file guiOptionBox\&.h\&.
.SS "\fBguiComposite_s\fP* guiOption::state[\fBGUI_OPTION_STATE_COUNT\fP]"

.PP
Definition at line 26 of file guiOptionBox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
