.TH "guiBackground" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiBackground
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gui\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBg2dColor_t\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBg2dImage_s\fP * \fBimg\fP"
.br
.ti -1c
.RI "\fBg2dCoord_s\fP \fBpdest\fP"
.br
.ti -1c
.RI "\fBguiBackgroundFN_f\fP \fBfn\fP"
.br
.ti -1c
.RI "unsigned \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file gui\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBg2dColor_t\fP guiBackground::color"

.PP
Definition at line 72 of file gui\&.h\&.
.SS "\fBguiBackgroundFN_f\fP guiBackground::fn"

.PP
Definition at line 75 of file gui\&.h\&.
.SS "\fBg2dImage_s\fP* guiBackground::img"

.PP
Definition at line 73 of file gui\&.h\&.
.SS "unsigned guiBackground::mode"

.PP
Definition at line 76 of file gui\&.h\&.
.SS "\fBg2dCoord_s\fP guiBackground::pdest"

.PP
Definition at line 74 of file gui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
