.TH "guiButton" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiButton\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBguiLabel_s\fP * \fBlabel\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBonclick\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBparentKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file guiButton\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBguiLabel_s\fP* guiButton::label"

.PP
Definition at line 11 of file guiButton\&.h\&.
.SS "\fBguiEvent_f\fP guiButton::onclick"

.PP
Definition at line 12 of file guiButton\&.h\&.
.SS "\fBguiEvent_f\fP guiButton::parentKey"

.PP
Definition at line 13 of file guiButton\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
