.TH "gui" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gui\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBclass\fP"
.br
.ti -1c
.RI "struct \fBgui\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBgui\fP ** \fBchilds\fP"
.br
.ti -1c
.RI "void * \fBcontrol\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "xcb_window_t \fBid\fP"
.br
.ti -1c
.RI "int \fBfocusable\fP"
.br
.ti -1c
.RI "int \fBbordersize\fP"
.br
.ti -1c
.RI "int \fBbordersizefocused\fP"
.br
.ti -1c
.RI "int \fBvisible\fP"
.br
.ti -1c
.RI "\fBg2dColor_t\fP \fBborderColor\fP"
.br
.ti -1c
.RI "\fBxorgSurface_s\fP * \fBsurface\fP"
.br
.ti -1c
.RI "\fBguiPosition_s\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBguiScene_s\fP \fBscene\fP"
.br
.ti -1c
.RI "\fBguiMargin_s\fP \fBuserMargin\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBdestroy\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBfree\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBredraw\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBdraw\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBmouse\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBfocus\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBmap\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBmove\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBatom\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBclient\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBclipboard\fP"
.br
.ti -1c
.RI "\fBguiEvent_f\fP \fBthemes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file gui\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBguiEvent_f\fP gui::atom"

.PP
Definition at line 146 of file gui\&.h\&.
.SS "\fBg2dColor_t\fP gui::borderColor"

.PP
Definition at line 129 of file gui\&.h\&.
.SS "int gui::bordersize"

.PP
Definition at line 126 of file gui\&.h\&.
.SS "int gui::bordersizefocused"

.PP
Definition at line 127 of file gui\&.h\&.
.SS "struct \fBgui\fP** gui::childs"

.PP
Definition at line 118 of file gui\&.h\&.
.SS "char* gui::class"

.PP
Definition at line 116 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::client"

.PP
Definition at line 147 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::clipboard"

.PP
Definition at line 148 of file gui\&.h\&.
.SS "void* gui::control"

.PP
Definition at line 120 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::create"

.PP
Definition at line 136 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::destroy"

.PP
Definition at line 137 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::draw"

.PP
Definition at line 140 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::focus"

.PP
Definition at line 143 of file gui\&.h\&.
.SS "int gui::focusable"

.PP
Definition at line 125 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::free"

.PP
Definition at line 138 of file gui\&.h\&.
.SS "xcb_window_t gui::id"

.PP
Definition at line 124 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::key"

.PP
Definition at line 141 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::map"

.PP
Definition at line 144 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::mouse"

.PP
Definition at line 142 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::move"

.PP
Definition at line 145 of file gui\&.h\&.
.SS "char* gui::name"

.PP
Definition at line 115 of file gui\&.h\&.
.SS "struct \fBgui\fP* gui::parent"

.PP
Definition at line 117 of file gui\&.h\&.
.SS "\fBguiPosition_s\fP gui::position"

.PP
Definition at line 132 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::redraw"

.PP
Definition at line 139 of file gui\&.h\&.
.SS "\fBguiScene_s\fP gui::scene"

.PP
Definition at line 133 of file gui\&.h\&.
.SS "\fBxorgSurface_s\fP* gui::surface"

.PP
Definition at line 131 of file gui\&.h\&.
.SS "\fBguiEvent_f\fP gui::themes"

.PP
Definition at line 149 of file gui\&.h\&.
.SS "int gui::type"

.PP
Definition at line 123 of file gui\&.h\&.
.SS "void* gui::userdata"

.PP
Definition at line 121 of file gui\&.h\&.
.SS "\fBguiMargin_s\fP gui::userMargin"

.PP
Definition at line 134 of file gui\&.h\&.
.SS "int gui::visible"

.PP
Definition at line 128 of file gui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
