.TH "gif" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gif
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imageGif\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBwidth\fP"
.br
.ti -1c
.RI "unsigned \fBheight\fP"
.br
.ti -1c
.RI "\fBgifFrame_s\fP * \fBframes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file imageGif\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBgifFrame_s\fP* gif::frames"
vector of gifFrame_s 
.PP
Definition at line 17 of file imageGif\&.h\&.
.SS "unsigned gif::height"

.PP
Definition at line 16 of file imageGif\&.h\&.
.SS "unsigned gif::width"

.PP
Definition at line 15 of file imageGif\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
