.TH "guiTimer_s" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiTimer_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gui\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBms\fP"
.br
.ti -1c
.RI "size_t \fBraisedon\fP"
.br
.ti -1c
.RI "\fBgui_s\fP * \fBgui\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "\fBguiTimer_f\fP \fBfn\fP"
.br
.ti -1c
.RI "\fBphqElement_s\fP * \fBel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file gui\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBphqElement_s\fP* guiTimer_s::el"

.PP
Definition at line 101 of file gui\&.h\&.
.SS "\fBguiTimer_f\fP guiTimer_s::fn"

.PP
Definition at line 100 of file gui\&.h\&.
.SS "\fBgui_s\fP* guiTimer_s::gui"

.PP
Definition at line 98 of file gui\&.h\&.
.SS "size_t guiTimer_s::ms"

.PP
Definition at line 96 of file gui\&.h\&.
.SS "size_t guiTimer_s::raisedon"

.PP
Definition at line 97 of file gui\&.h\&.
.SS "void* guiTimer_s::userdata"

.PP
Definition at line 99 of file gui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
