.TH "guiPosition" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiPosition
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gui\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "unsigned \fBw\fP"
.br
.ti -1c
.RI "unsigned \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file gui\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned guiPosition::h"

.PP
Definition at line 59 of file gui\&.h\&.
.SS "unsigned guiPosition::w"

.PP
Definition at line 59 of file gui\&.h\&.
.SS "int guiPosition::x"

.PP
Definition at line 58 of file gui\&.h\&.
.SS "int guiPosition::y"

.PP
Definition at line 58 of file gui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
