.TH "guiLabel" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiLabel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBguiCaption_s\fP * \fBcaption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file guiLabel\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBguiCaption_s\fP* guiLabel::caption"

.PP
Definition at line 8 of file guiLabel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
