.TH "include/ef/guiLabel.h" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ef/guiLabel.h
.SH SYNOPSIS
.br
.PP
\fC#include <ef/gui\&.h>\fP
.br
\fC#include <ef/guiCaption\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBguiLabel\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBguiLabel\fP \fBguiLabel_s\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBguiLabel_s\fP * \fBgui_label_new\fP (\fBguiCaption_s\fP *caption)"
.br
.ti -1c
.RI "\fBgui_s\fP * \fBgui_label_attach\fP (\fBgui_s\fP *\fBgui\fP, \fBguiLabel_s\fP *lbl)"
.br
.ti -1c
.RI "void \fBgui_label_free\fP (\fBguiLabel_s\fP *lbl)"
.br
.ti -1c
.RI "void \fBgui_label_text_set\fP (\fBgui_s\fP *\fBgui\fP, const \fButf8_t\fP *text)"
.br
.ti -1c
.RI "void \fBgui_label_redraw\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_label_scroll\fP (\fBgui_s\fP *\fBgui\fP, unsigned x, unsigned y)"
.br
.ti -1c
.RI "int \fBgui_label_event_free\fP (\fBgui_s\fP *\fBgui\fP, \fB__unused\fP \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_label_event_redraw\fP (\fBgui_s\fP *\fBgui\fP, \fB__unused\fP \fBxorgEvent_s\fP *unset)"
.br
.ti -1c
.RI "int \fBgui_label_event_themes\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_label_event_move\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *\fBevent\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBguiLabel\fP \fBguiLabel_s\fP"

.SH "Function Documentation"
.PP 
.SS "\fBgui_s\fP* gui_label_attach (\fBgui_s\fP * gui, \fBguiLabel_s\fP * lbl)"
attach label to gui 
.SS "int gui_label_event_free (\fBgui_s\fP * gui, \fB__unused\fP \fBxorgEvent_s\fP * ev)"
event free 
.SS "int gui_label_event_move (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * event)"

.SS "int gui_label_event_redraw (\fBgui_s\fP * gui, \fB__unused\fP \fBxorgEvent_s\fP * unset)"
event redraw 
.SS "int gui_label_event_themes (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * ev)"
event themes 
.SS "void gui_label_free (\fBguiLabel_s\fP * lbl)"
label free 
.SS "\fBguiLabel_s\fP* gui_label_new (\fBguiCaption_s\fP * caption)"
create new label 
.SS "void gui_label_redraw (\fBgui_s\fP * gui)"
label redraw event 
.SS "void gui_label_scroll (\fBgui_s\fP * gui, unsigned x, unsigned y)"
label scroll 
.SS "void gui_label_text_set (\fBgui_s\fP * gui, const \fButf8_t\fP * text)"
label set caption 
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
