.TH "include/ef/guiButton.h" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ef/guiButton.h
.SH SYNOPSIS
.br
.PP
\fC#include <ef/gui\&.h>\fP
.br
\fC#include <ef/guiCaption\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBguiButton\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGUI_BUTTON_STATE_NORMAL\fP   0"
.br
.ti -1c
.RI "#define \fBGUI_BUTTON_STATE_PRESS\fP   1"
.br
.ti -1c
.RI "#define \fBGUI_BUTTON_STATE_HOVER\fP   2"
.br
.ti -1c
.RI "#define \fBGUI_BUTTON_STATE_COUNT\fP   3"
.br
.ti -1c
.RI "#define \fBGUI_THEME_BUTTON_PRESS\fP   'press'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_BUTTON_HOVER\fP   'hover'"
.br
.ti -1c
.RI "#define \fBGUI_THEME_BUTTON_HOVER_ENABLE\fP   'hoverEnable'"
.br
.ti -1c
.RI "#define \fBGUI_BUTTON_FLAGS_HOVER\fP   0x01"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBguiButton\fP \fBguiButton_s\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBguiButton_s\fP * \fBgui_button_new\fP (\fBguiCaption_s\fP *caption, \fBguiComposite_s\fP *press, \fBguiComposite_s\fP *hover, \fBguiEvent_f\fP onclick, int flags)"
.br
.ti -1c
.RI "\fBgui_s\fP * \fBgui_button_attach\fP (\fBgui_s\fP *\fBgui\fP, \fBguiButton_s\fP *btn)"
.br
.ti -1c
.RI "void \fBgui_button_free\fP (\fBguiButton_s\fP *btn)"
.br
.ti -1c
.RI "void \fBgui_button_text_set\fP (\fBgui_s\fP *\fBgui\fP, const \fButf8_t\fP *text)"
.br
.ti -1c
.RI "const \fButf8_t\fP * \fBgui_button_text_get\fP (\fBgui_s\fP *\fBgui\fP)"
.br
.ti -1c
.RI "void \fBgui_button_redraw\fP (\fBgui_s\fP *\fBgui\fP, unsigned normalPressHover)"
.br
.ti -1c
.RI "int \fBgui_button_event_free\fP (\fBgui_s\fP *\fBgui\fP, \fB__unused\fP \fBxorgEvent_s\fP *ev)"
.br
.ti -1c
.RI "int \fBgui_button_event_redraw\fP (\fBgui_s\fP *\fBgui\fP, \fB__unused\fP \fBxorgEvent_s\fP *unset)"
.br
.ti -1c
.RI "int \fBgui_button_event_key\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *\fBevent\fP)"
.br
.ti -1c
.RI "int \fBgui_button_event_mouse\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *\fBevent\fP)"
.br
.ti -1c
.RI "int \fBgui_button_event_move\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *\fBevent\fP)"
.br
.ti -1c
.RI "int \fBgui_button_event_themes\fP (\fBgui_s\fP *\fBgui\fP, \fBxorgEvent_s\fP *ev)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GUI_BUTTON_FLAGS_HOVER   0x01"

.PP
Definition at line 17 of file guiButton\&.h\&.
.SS "#define GUI_BUTTON_STATE_COUNT   3"

.PP
Definition at line 11 of file guiButton\&.h\&.
.SS "#define GUI_BUTTON_STATE_HOVER   2"

.PP
Definition at line 10 of file guiButton\&.h\&.
.SS "#define GUI_BUTTON_STATE_NORMAL   0"

.PP
Definition at line 8 of file guiButton\&.h\&.
.SS "#define GUI_BUTTON_STATE_PRESS   1"

.PP
Definition at line 9 of file guiButton\&.h\&.
.SS "#define GUI_THEME_BUTTON_HOVER   'hover'"

.PP
Definition at line 14 of file guiButton\&.h\&.
.SS "#define GUI_THEME_BUTTON_HOVER_ENABLE   'hoverEnable'"

.PP
Definition at line 15 of file guiButton\&.h\&.
.SS "#define GUI_THEME_BUTTON_PRESS   'press'"

.PP
Definition at line 13 of file guiButton\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBguiButton\fP \fBguiButton_s\fP"

.SH "Function Documentation"
.PP 
.SS "\fBgui_s\fP* gui_button_attach (\fBgui_s\fP * gui, \fBguiButton_s\fP * btn)"
attach button to gui 
.SS "int gui_button_event_free (\fBgui_s\fP * gui, \fB__unused\fP \fBxorgEvent_s\fP * ev)"
button free event 
.SS "int gui_button_event_key (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * event)"
button event key 
.SS "int gui_button_event_mouse (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * event)"
button event mouse 
.SS "int gui_button_event_move (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * event)"

.SS "int gui_button_event_redraw (\fBgui_s\fP * gui, \fB__unused\fP \fBxorgEvent_s\fP * unset)"
button redraw event 
.SS "int gui_button_event_themes (\fBgui_s\fP * gui, \fBxorgEvent_s\fP * ev)"
button event theme 
.SS "void gui_button_free (\fBguiButton_s\fP * btn)"
free button 
.SS "\fBguiButton_s\fP* gui_button_new (\fBguiCaption_s\fP * caption, \fBguiComposite_s\fP * press, \fBguiComposite_s\fP * hover, \fBguiEvent_f\fP onclick, int flags)"
create new button 
.SS "void gui_button_redraw (\fBgui_s\fP * gui, unsigned normalPressHover)"
button redraw 
.SS "const \fButf8_t\fP* gui_button_text_get (\fBgui_s\fP * gui)"
get button text 
.SS "void gui_button_text_set (\fBgui_s\fP * gui, const \fButf8_t\fP * text)"
button set text 
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
