.TH "g2dImage" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
g2dImage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <image\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBpixel\fP"
.br
.ti -1c
.RI "unsigned \fBw\fP"
.br
.ti -1c
.RI "unsigned \fBh\fP"
.br
.ti -1c
.RI "unsigned \fBp\fP"
.br
.ti -1c
.RI "unsigned \fBsa\fP"
.br
.ti -1c
.RI "unsigned \fBsr\fP"
.br
.ti -1c
.RI "unsigned \fBsg\fP"
.br
.ti -1c
.RI "unsigned \fBsb\fP"
.br
.ti -1c
.RI "unsigned \fBma\fP"
.br
.ti -1c
.RI "unsigned \fBmr\fP"
.br
.ti -1c
.RI "unsigned \fBmg\fP"
.br
.ti -1c
.RI "unsigned \fBmb\fP"
.br
.ti -1c
.RI "\fBg2dMode_e\fP \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file image\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned g2dImage::h"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::ma"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::mb"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::mg"

.PP
Definition at line 13 of file image\&.h\&.
.SS "\fBg2dMode_e\fP g2dImage::mode"

.PP
Definition at line 14 of file image\&.h\&.
.SS "unsigned g2dImage::mr"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::p"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned char* g2dImage::pixel"

.PP
Definition at line 12 of file image\&.h\&.
.SS "unsigned g2dImage::sa"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::sb"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::sg"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::sr"

.PP
Definition at line 13 of file image\&.h\&.
.SS "unsigned g2dImage::w"

.PP
Definition at line 13 of file image\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
