.TH "guiBar" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiBar
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiBar\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBguiCaption_s\fP * \fBcaption\fP"
.br
.ti -1c
.RI "\fBguiLayer_s\fP * \fBfill\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBtextdescript\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBcurrentdescript\fP"
.br
.ti -1c
.RI "double \fBmin\fP"
.br
.ti -1c
.RI "double \fBmax\fP"
.br
.ti -1c
.RI "double \fBcurrent\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file guiBar\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBguiCaption_s\fP* guiBar::caption"

.PP
Definition at line 23 of file guiBar\&.h\&.
.SS "double guiBar::current"

.PP
Definition at line 29 of file guiBar\&.h\&.
.SS "\fButf8_t\fP* guiBar::currentdescript"

.PP
Definition at line 26 of file guiBar\&.h\&.
.SS "\fBguiLayer_s\fP* guiBar::fill"

.PP
Definition at line 24 of file guiBar\&.h\&.
.SS "unsigned guiBar::flags"

.PP
Definition at line 30 of file guiBar\&.h\&.
.SS "double guiBar::max"

.PP
Definition at line 28 of file guiBar\&.h\&.
.SS "double guiBar::min"

.PP
Definition at line 27 of file guiBar\&.h\&.
.SS "\fButf8_t\fP* guiBar::textdescript"

.PP
Definition at line 25 of file guiBar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
