.TH "guiCaption" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guiCaption
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiCaption\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBguiLayer_s\fP * \fBrender\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBscroll\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBtext\fP"
.br
.ti -1c
.RI "unsigned \fBtextWidth\fP"
.br
.ti -1c
.RI "unsigned \fBtextHeight\fP"
.br
.ti -1c
.RI "\fBftFonts_s\fP * \fBfonts\fP"
.br
.ti -1c
.RI "\fBg2dColor_t\fP \fBforeground\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file guiCaption\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned guiCaption::flags"

.PP
Definition at line 21 of file guiCaption\&.h\&.
.SS "\fBftFonts_s\fP* guiCaption::fonts"

.PP
Definition at line 26 of file guiCaption\&.h\&.
.SS "\fBg2dColor_t\fP guiCaption::foreground"

.PP
Definition at line 27 of file guiCaption\&.h\&.
.SS "\fBguiLayer_s\fP* guiCaption::render"

.PP
Definition at line 20 of file guiCaption\&.h\&.
.SS "\fBg2dPoint_s\fP guiCaption::scroll"

.PP
Definition at line 22 of file guiCaption\&.h\&.
.SS "\fButf8_t\fP* guiCaption::text"

.PP
Definition at line 23 of file guiCaption\&.h\&.
.SS "unsigned guiCaption::textHeight"

.PP
Definition at line 25 of file guiCaption\&.h\&.
.SS "unsigned guiCaption::textWidth"

.PP
Definition at line 24 of file guiCaption\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
