.TH "g2dCoord" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
g2dCoord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <image\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBx\fP"
.br
.ti -1c
.RI "unsigned \fBy\fP"
.br
.ti -1c
.RI "unsigned \fBw\fP"
.br
.ti -1c
.RI "unsigned \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file image\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned g2dCoord::h"

.PP
Definition at line 20 of file image\&.h\&.
.SS "unsigned g2dCoord::w"

.PP
Definition at line 20 of file image\&.h\&.
.SS "unsigned g2dCoord::x"

.PP
Definition at line 20 of file image\&.h\&.
.SS "unsigned g2dCoord::y"

.PP
Definition at line 20 of file image\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
