.TH "gifFrame" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gifFrame
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imageGif\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBg2dCoord_s\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBg2dImage_s\fP * \fBimg\fP"
.br
.ti -1c
.RI "unsigned \fBdelay\fP"
.br
.ti -1c
.RI "unsigned \fBdispose\fP"
.br
.ti -1c
.RI "int \fBtransindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file imageGif\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned gifFrame::delay"
delay in ms 
.PP
Definition at line 9 of file imageGif\&.h\&.
.SS "unsigned gifFrame::dispose"

.PP
Definition at line 10 of file imageGif\&.h\&.
.SS "\fBg2dImage_s\fP* gifFrame::img"
image to display 
.PP
Definition at line 8 of file imageGif\&.h\&.
.SS "\fBg2dCoord_s\fP gifFrame::pos"

.PP
Definition at line 7 of file imageGif\&.h\&.
.SS "int gifFrame::transindex"

.PP
Definition at line 11 of file imageGif\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
