.TH "http" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <http\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBwww_s\fP \fBwww\fP"
.br
.ti -1c
.RI "\fBhttpPost_s\fP \fBpost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file http\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBhttpPost_s\fP http::post"

.PP
Definition at line 16 of file http\&.h\&.
.SS "\fBwww_s\fP http::www"

.PP
Definition at line 15 of file http\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
