.TH "httpPost" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httpPost
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <http\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct curl_httppost * \fBpost\fP"
.br
.ti -1c
.RI "struct curl_httppost * \fBlast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file http\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct curl_httppost* httpPost::last"

.PP
Definition at line 11 of file http\&.h\&.
.SS "struct curl_httppost* httpPost::post"

.PP
Definition at line 10 of file http\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
