.TH "include/ef/imageJpeg.h" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ef/imageJpeg.h
.SH SYNOPSIS
.br
.PP
\fC#include <ef/image\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBg2dImage_s\fP * \fBg2d_load_jpeg\fP (char const *path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBg2dImage_s\fP* g2d_load_jpeg (char const * path)"
load jpeg image, set errno to 666 if not a jpeg image 
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
