.TH "imapMime" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imapMime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBxauth\fP"
.br
.ti -1c
.RI "int \fBxsid\fP"
.br
.ti -1c
.RI "char * \fBfrom\fP"
.br
.ti -1c
.RI "char * \fBto\fP"
.br
.ti -1c
.RI "char * \fBreplyto\fP"
.br
.ti -1c
.RI "char * \fBdate\fP"
.br
.ti -1c
.RI "char * \fBsubject\fP"
.br
.ti -1c
.RI "char * \fBboundary\fP"
.br
.ti -1c
.RI "\fBimapMimeContent_s\fP * \fBcontent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file imap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* imapMime::boundary"
boundary, its used for farse content 
.PP
Definition at line 34 of file imap\&.h\&.
.SS "\fBimapMimeContent_s\fP* imapMime::content"
all content 
.PP
Definition at line 35 of file imap\&.h\&.
.SS "char* imapMime::date"
date message 
.PP
Definition at line 32 of file imap\&.h\&.
.SS "char* imapMime::from"
from eamil 
.PP
Definition at line 29 of file imap\&.h\&.
.SS "char* imapMime::replyto"
reply from 
.PP
Definition at line 31 of file imap\&.h\&.
.SS "char* imapMime::subject"
subject 
.PP
Definition at line 33 of file imap\&.h\&.
.SS "char* imapMime::to"
to email 
.PP
Definition at line 30 of file imap\&.h\&.
.SS "int imapMime::xauth"
xaut pass/fail 
.PP
Definition at line 27 of file imap\&.h\&.
.SS "int imapMime::xsid"
xsid pass/fail 
.PP
Definition at line 28 of file imap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
