.TH "imapFetch" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imapFetch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBid\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "const char * \fBmime\fP"
.br
.ti -1c
.RI "\fBimapFetchFlags_e\fP \fBflag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file imap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBimapFetchFlags_e\fP imapFetch::flag"
flag 
.PP
Definition at line 42 of file imap\&.h\&.
.SS "size_t imapFetch::id"
id 
.PP
Definition at line 39 of file imap\&.h\&.
.SS "const char* imapFetch::mime"
unparsed mime 
.PP
Definition at line 41 of file imap\&.h\&.
.SS "size_t imapFetch::size"
size of fetch 
.PP
Definition at line 40 of file imap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
