.TH "imapExamine" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imapExamine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBexists\fP"
.br
.ti -1c
.RI "size_t \fBrecent\fP"
.br
.ti -1c
.RI "size_t \fBunseeid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file imap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t imapExamine::exists"
exists mexage, exists id is most recent message 
.PP
Definition at line 46 of file imap\&.h\&.
.SS "size_t imapExamine::recent"
recent 
.PP
Definition at line 47 of file imap\&.h\&.
.SS "size_t imapExamine::unseeid"
first unsee id 
.PP
Definition at line 48 of file imap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
