.TH "imap" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBwww_s\fP \fBwww\fP"
.br
.ti -1c
.RI "char * \fBserver\fP"
.br
.ti -1c
.RI "size_t \fBlenServer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file imap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t imap::lenServer"

.PP
Definition at line 54 of file imap\&.h\&.
.SS "char* imap::server"

.PP
Definition at line 53 of file imap\&.h\&.
.SS "\fBwww_s\fP imap::www"

.PP
Definition at line 52 of file imap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
