.TH "kbData" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kbData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminfo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtiData_s\fP * \fBtid\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "size_t \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file terminfo\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t kbData::id"

.PP
Definition at line 47 of file terminfo\&.h\&.
.SS "char* kbData::name"

.PP
Definition at line 46 of file terminfo\&.h\&.
.SS "\fBtiData_s\fP* kbData::tid"

.PP
Definition at line 45 of file terminfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
