.TH "listDouble" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listDouble
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBnext\fP"
.br
.ti -1c
.RI "void * \fBprev\fP"
.br
.ti -1c
.RI "\fBlistFree_f\fP \fBclean\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "void * \fBdata\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBlistFree_f\fP listDouble::clean"
cleanup function 
.PP
Definition at line 132 of file list\&.h\&.
.SS "void* listDouble::data[0]"
user data 
.PP
Definition at line 134 of file list\&.h\&.
.SS "void* listDouble::next"
next element 
.PP
Definition at line 130 of file list\&.h\&.
.SS "void* listDouble::prev"
prev element 
.PP
Definition at line 131 of file list\&.h\&.
.SS "size_t listDouble::size"
size data 
.PP
Definition at line 133 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
