.TH "listSimple" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listSimple
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBnext\fP"
.br
.ti -1c
.RI "\fBlistFree_f\fP \fBclean\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "void * \fBdata\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBlistFree_f\fP listSimple::clean"
cleanup function 
.PP
Definition at line 18 of file list\&.h\&.
.SS "void* listSimple::data[0]"
user data 
.PP
Definition at line 20 of file list\&.h\&.
.SS "void* listSimple::next"
next element 
.PP
Definition at line 17 of file list\&.h\&.
.SS "size_t listSimple::size"
size of data 
.PP
Definition at line 19 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
