.TH "message" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threads\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBmessage\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBqmfree_f\fP \fBclean\fP"
.br
.ti -1c
.RI "void * \fBdata\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file threads\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBqmfree_f\fP message::clean"

.PP
Definition at line 164 of file threads\&.h\&.
.SS "void* message::data[0]"

.PP
Definition at line 165 of file threads\&.h\&.
.SS "struct \fBmessage\fP* message::next"

.PP
Definition at line 163 of file threads\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
