.TH "memInfo" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <proc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBtotal\fP"
.br
.ti -1c
.RI "size_t \fBfree\fP"
.br
.ti -1c
.RI "size_t \fBavailable\fP"
.br
.ti -1c
.RI "size_t \fBbuffers\fP"
.br
.ti -1c
.RI "size_t \fBcached\fP"
.br
.ti -1c
.RI "size_t \fBtotalswap\fP"
.br
.ti -1c
.RI "size_t \fBfreeswap\fP"
.br
.ti -1c
.RI "size_t \fBshared\fP"
.br
.ti -1c
.RI "size_t \fBSReclaimable\fP"
.br
.ti -1c
.RI "size_t \fBSUnreclaim\fP"
.br
.ti -1c
.RI "size_t \fBused\fP"
.br
.ti -1c
.RI "size_t \fBtoblink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file proc\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t memInfo::available"

.PP
Definition at line 21 of file proc\&.h\&.
.SS "size_t memInfo::buffers"

.PP
Definition at line 22 of file proc\&.h\&.
.SS "size_t memInfo::cached"

.PP
Definition at line 23 of file proc\&.h\&.
.SS "size_t memInfo::free"

.PP
Definition at line 20 of file proc\&.h\&.
.SS "size_t memInfo::freeswap"

.PP
Definition at line 25 of file proc\&.h\&.
.SS "size_t memInfo::shared"

.PP
Definition at line 26 of file proc\&.h\&.
.SS "size_t memInfo::SReclaimable"

.PP
Definition at line 27 of file proc\&.h\&.
.SS "size_t memInfo::SUnreclaim"

.PP
Definition at line 28 of file proc\&.h\&.
.SS "size_t memInfo::toblink"

.PP
Definition at line 30 of file proc\&.h\&.
.SS "size_t memInfo::total"

.PP
Definition at line 19 of file proc\&.h\&.
.SS "size_t memInfo::totalswap"

.PP
Definition at line 24 of file proc\&.h\&.
.SS "size_t memInfo::used"

.PP
Definition at line 29 of file proc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
