.TH "message" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threads\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "void * \fBdata\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file threads\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* message::data[0]"

.PP
Definition at line 173 of file threads\&.h\&.
.SS "int message::id"

.PP
Definition at line 171 of file threads\&.h\&.
.SS "int message::type"

.PP
Definition at line 172 of file threads\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
