.TH "netDev" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netDev
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <proc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBreceive\fP [\fBND_COUNT\fP]"
.br
.ti -1c
.RI "size_t \fBtransmit\fP [\fBND_COUNT\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file proc\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t netDev::receive[\fBND_COUNT\fP]"

.PP
Definition at line 36 of file proc\&.h\&.
.SS "size_t netDev::transmit[\fBND_COUNT\fP]"

.PP
Definition at line 37 of file proc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
