.TH "oauth2Authorization" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oauth2Authorization
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <oauth\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBauthorizationLink\fP"
.br
.ti -1c
.RI "const char * \fBtokenLink\fP"
.br
.ti -1c
.RI "const char * \fBrefreshTokenLink\fP"
.br
.ti -1c
.RI "const char * \fBhttpReplyOk\fP"
.br
.ti -1c
.RI "const char * \fBhttpReplyError\fP"
.br
.ti -1c
.RI "const char * \fBappClientId\fP"
.br
.ti -1c
.RI "const char * \fBappClientSecret\fP"
.br
.ti -1c
.RI "const char * \fBscope\fP"
.br
.ti -1c
.RI "const char * \fBaccessType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file oauth\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char* oauth2Authorization::accessType"

.PP
Definition at line 18 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::appClientId"

.PP
Definition at line 15 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::appClientSecret"

.PP
Definition at line 16 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::authorizationLink"

.PP
Definition at line 10 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::httpReplyError"

.PP
Definition at line 14 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::httpReplyOk"

.PP
Definition at line 13 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::refreshTokenLink"

.PP
Definition at line 12 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::scope"

.PP
Definition at line 17 of file oauth\&.h\&.
.SS "const char* oauth2Authorization::tokenLink"

.PP
Definition at line 11 of file oauth\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
