.TH "oauth2" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oauth2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <oauth\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhttp_s\fP * \fBhttp\fP"
.br
.ti -1c
.RI "char * \fBcodeReply\fP"
.br
.ti -1c
.RI "char * \fBtoken\fP"
.br
.ti -1c
.RI "char * \fBtokenRefresh\fP"
.br
.ti -1c
.RI "char * \fBscope\fP"
.br
.ti -1c
.RI "char \fBrndStr\fP [\fBOAUTH_RND_STR_SIZE\fP]"
.br
.ti -1c
.RI "size_t \fBexpires\fP"
.br
.ti -1c
.RI "time_t \fBexpiresTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file oauth\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* oauth2::codeReply"

.PP
Definition at line 23 of file oauth\&.h\&.
.SS "size_t oauth2::expires"

.PP
Definition at line 28 of file oauth\&.h\&.
.SS "time_t oauth2::expiresTime"

.PP
Definition at line 29 of file oauth\&.h\&.
.SS "\fBhttp_s\fP* oauth2::http"

.PP
Definition at line 22 of file oauth\&.h\&.
.SS "char oauth2::rndStr[\fBOAUTH_RND_STR_SIZE\fP]"

.PP
Definition at line 27 of file oauth\&.h\&.
.SS "char* oauth2::scope"

.PP
Definition at line 26 of file oauth\&.h\&.
.SS "char* oauth2::token"

.PP
Definition at line 24 of file oauth\&.h\&.
.SS "char* oauth2::tokenRefresh"

.PP
Definition at line 25 of file oauth\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
