.TH "include/ef/os.h" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ef/os.h
.SH SYNOPSIS
.br
.PP
\fC#include <ef/type\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBos_setlocale\fP (int category, const char *locale)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* os_setlocale (int category, const char * locale)"
set locale and return previous setting 
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
