.TH "include/ef/os.h" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ef/os.h
.SH SYNOPSIS
.br
.PP
\fC#include <ef/type\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBos_getlocale\fP()   locale_charset()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBos_setlocale\fP (int category, const char *locale)"
.br
.ti -1c
.RI "void \fBos_begin\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define os_getlocale()   locale_charset()"
get current locale 
.PP
Definition at line 11 of file os\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void os_begin (void)"

.SS "const char* os_setlocale (int category, const char * locale)"
set locale and return previous setting 
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
