.TH "phq" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phq
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <phq\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBresize\fP"
.br
.ti -1c
.RI "\fBphqCompare_f\fP \fBcmp\fP"
.br
.ti -1c
.RI "\fBphqElement_s\fP ** \fBelements\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file phq\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBphqCompare_f\fP phq::cmp"
compare function 
.PP
Definition at line 22 of file phq\&.h\&.
.SS "size_t phq::count"
count elements 
.PP
Definition at line 20 of file phq\&.h\&.
.SS "\fBphqElement_s\fP** phq::elements"
array of elements 
.PP
Definition at line 23 of file phq\&.h\&.
.SS "size_t phq::resize"
resize 
.PP
Definition at line 21 of file phq\&.h\&.
.SS "size_t phq::size"
size of elements 
.PP
Definition at line 19 of file phq\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
