.TH "phqElement" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phqElement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <phq\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBpriority\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.ti -1c
.RI "\fBphqFree_f\fP \fBfree\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file phq\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* phqElement::data"
userdata 
.PP
Definition at line 15 of file phq\&.h\&.
.SS "\fBphqFree_f\fP phqElement::free"
callback function 
.PP
Definition at line 14 of file phq\&.h\&.
.SS "size_t phqElement::index"
index 
.PP
Definition at line 13 of file phq\&.h\&.
.SS "size_t phqElement::priority"
priority 
.PP
Definition at line 12 of file phq\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
