.TH "pollEvent" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pollEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deadpoll\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBevent\fP"
.br
.ti -1c
.RI "\fBpollCbk_f\fP \fBcallback\fP"
.br
.ti -1c
.RI "void * \fBarg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file deadpoll\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* pollEvent::arg"

.PP
Definition at line 28 of file deadpoll\&.h\&.
.SS "\fBpollCbk_f\fP pollEvent::callback"

.PP
Definition at line 27 of file deadpoll\&.h\&.
.SS "int pollEvent::event"

.PP
Definition at line 26 of file deadpoll\&.h\&.
.SS "int pollEvent::fd"

.PP
Definition at line 25 of file deadpoll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
