.TH "powerstate" 3 "Tue Mar 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
powerstate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sys\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBvoltageMin\fP"
.br
.ti -1c
.RI "size_t \fBvoltageNow\fP"
.br
.ti -1c
.RI "size_t \fBenergyFull\fP"
.br
.ti -1c
.RI "size_t \fBenergyNow\fP"
.br
.ti -1c
.RI "size_t \fBpowerNow\fP"
.br
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.ti -1c
.RI "double \fBtimeleft\fP"
.br
.ti -1c
.RI "char * \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file sys\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t powerstate::capacity"
% 
.PP
Definition at line 13 of file sys\&.h\&.
.SS "size_t powerstate::energyFull"
uW/h 
.PP
Definition at line 10 of file sys\&.h\&.
.SS "size_t powerstate::energyNow"
uW/h 
.PP
Definition at line 11 of file sys\&.h\&.
.SS "size_t powerstate::powerNow"
uW 
.PP
Definition at line 12 of file sys\&.h\&.
.SS "char* powerstate::status"

.PP
Definition at line 15 of file sys\&.h\&.
.SS "double powerstate::timeleft"
s 
.PP
Definition at line 14 of file sys\&.h\&.
.SS "size_t powerstate::voltageMin"
uV 
.PP
Definition at line 8 of file sys\&.h\&.
.SS "size_t powerstate::voltageNow"
uV 
.PP
Definition at line 9 of file sys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
