.TH "regex" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
regex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <regex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pcre2_code * \fBrx\fP"
.br
.ti -1c
.RI "pcre2_match_data * \fBmatch\fP"
.br
.ti -1c
.RI "PCRE2_SIZE * \fBoffv\fP"
.br
.ti -1c
.RI "size_t \fBoffc\fP"
.br
.ti -1c
.RI "const char * \fBregex\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.ti -1c
.RI "size_t \fBlent\fP"
.br
.ti -1c
.RI "unsigned int \fBnewline\fP"
.br
.ti -1c
.RI "int \fButf8\fP"
.br
.ti -1c
.RI "int \fBcrlf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file regex\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int regex::crlf"

.PP
Definition at line 20 of file regex\&.h\&.
.SS "size_t regex::lent"

.PP
Definition at line 17 of file regex\&.h\&.
.SS "pcre2_match_data* regex::match"

.PP
Definition at line 12 of file regex\&.h\&.
.SS "unsigned int regex::newline"

.PP
Definition at line 18 of file regex\&.h\&.
.SS "size_t regex::offc"

.PP
Definition at line 14 of file regex\&.h\&.
.SS "PCRE2_SIZE* regex::offv"

.PP
Definition at line 13 of file regex\&.h\&.
.SS "const char* regex::regex"

.PP
Definition at line 15 of file regex\&.h\&.
.SS "pcre2_code* regex::rx"

.PP
Definition at line 11 of file regex\&.h\&.
.SS "const char* regex::text"

.PP
Definition at line 16 of file regex\&.h\&.
.SS "int regex::utf8"

.PP
Definition at line 19 of file regex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
