.TH "rbhashElement" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rbhashElement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rbhash\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "uint32_t \fBhash\fP"
.br
.ti -1c
.RI "uint32_t \fBlen\fP"
.br
.ti -1c
.RI "uint16_t \fBdistance\fP"
.br
.ti -1c
.RI "char \fBkey\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file rbhash\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* rbhashElement::data"
user data 
.PP
Definition at line 11 of file rbhash\&.h\&.
.SS "uint16_t rbhashElement::distance"
distance from hash 
.PP
Definition at line 14 of file rbhash\&.h\&.
.SS "uint32_t rbhashElement::hash"
hash 
.PP
Definition at line 12 of file rbhash\&.h\&.
.SS "char rbhashElement::key[]"
flexible key 
.PP
Definition at line 15 of file rbhash\&.h\&.
.SS "uint32_t rbhashElement::len"
len of key 
.PP
Definition at line 13 of file rbhash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
