.TH "rbuffer" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rbuffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rbuffer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsof\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBr\fP"
.br
.ti -1c
.RI "size_t \fBw\fP"
.br
.ti -1c
.RI "void * \fBelement\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
generic ring buffer 
.PP
Definition at line 7 of file rbuffer\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* rbuffer::element[0]"
memory 
.PP
Definition at line 12 of file rbuffer\&.h\&.
.SS "size_t rbuffer::r"
read id 
.PP
Definition at line 10 of file rbuffer\&.h\&.
.SS "size_t rbuffer::size"
size of memory 
.PP
Definition at line 9 of file rbuffer\&.h\&.
.SS "size_t rbuffer::sof"
sizeof type 
.PP
Definition at line 8 of file rbuffer\&.h\&.
.SS "size_t rbuffer::w"
write id 
.PP
Definition at line 11 of file rbuffer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
