.TH "svg" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
svg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imageSvg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "unsigned char * \fBmemblock\fP"
.br
.ti -1c
.RI "void * \fBrsvgHandle\fP"
.br
.ti -1c
.RI "unsigned \fBdimW\fP"
.br
.ti -1c
.RI "unsigned \fBdimH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file imageSvg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned svg::dimH"

.PP
Definition at line 11 of file imageSvg\&.h\&.
.SS "unsigned svg::dimW"

.PP
Definition at line 10 of file imageSvg\&.h\&.
.SS "unsigned char* svg::memblock"

.PP
Definition at line 8 of file imageSvg\&.h\&.
.SS "void* svg::rsvgHandle"

.PP
Definition at line 9 of file imageSvg\&.h\&.
.SS "size_t svg::size"

.PP
Definition at line 7 of file imageSvg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
