.TH "semaphore" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semaphore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threads\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfutex\fP"
.br
.ti -1c
.RI "int \fBprivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file threads\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int semaphore::futex"

.PP
Definition at line 78 of file threads\&.h\&.
.SS "int semaphore::private"

.PP
Definition at line 79 of file threads\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
