.TH "tuiList" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuiList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tuiList\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtuiListElement_s\fP * \fBelements\fP"
.br
.ti -1c
.RI "\fBtuiListMode_e\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBtuiListType_e\fP \fBtype\fP"
.br
.ti -1c
.RI "unsigned \fBsel\fP"
.br
.ti -1c
.RI "size_t \fBscrollRow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file tuiList\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtuiListElement_s\fP* tuiList::elements"

.PP
Definition at line 20 of file tuiList\&.h\&.
.SS "\fBtuiListMode_e\fP tuiList::mode"

.PP
Definition at line 21 of file tuiList\&.h\&.
.SS "size_t tuiList::scrollRow"

.PP
Definition at line 24 of file tuiList\&.h\&.
.SS "unsigned tuiList::sel"

.PP
Definition at line 23 of file tuiList\&.h\&.
.SS "\fBtuiListType_e\fP tuiList::type"

.PP
Definition at line 22 of file tuiList\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
