.TH "tiData" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tiData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminfo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtitype_e\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBstr\fP"
.br
.ti -1c
.RI "   int \fBnum\fP"
.br
.ti -1c
.RI "   \fBbool_t\fP \fBbol\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file terminfo\&.h\&.
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "\fBbool_t\fP tiData::bol"

.PP
Definition at line 41 of file terminfo\&.h\&.
.SS "int tiData::num"

.PP
Definition at line 40 of file terminfo\&.h\&.
.SS "char* tiData::str"

.PP
Definition at line 39 of file terminfo\&.h\&.
.SS "\fBtitype_e\fP tiData::type"

.PP
Definition at line 37 of file terminfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
