.TH "include/ef/term.h" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ef/term.h
.SH SYNOPSIS
.br
.PP
\fC#include <ef/type\&.h>\fP
.br
\fC#include <ef/terminfo\&.h>\fP
.br
\fC#include <ef/termcapstr\&.h>\fP
.br
\fC#include <ef/termlink\&.h>\fP
.br
\fC#include <ef/termmode\&.h>\fP
.br
\fC#include <ef/terminput\&.h>\fP
.br
\fC#include <ef/termreadline\&.h>\fP
.br
\fC#include <ef/termkey\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
