.TH "termKey" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminput\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf_t\fP \fBch\fP"
.br
.ti -1c
.RI "int \fBescape\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file terminput\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fButf_t\fP termKey::ch"

.PP
Definition at line 23 of file terminput\&.h\&.
.SS "int termKey::escape"

.PP
Definition at line 24 of file terminput\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
