.TH "trieElement" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trieElement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trie\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBcharset\fP"
.br
.ti -1c
.RI "struct \fBtrieElement\fP * \fBnext\fP"
.br
.ti -1c
.RI "void ** \fBendnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file trie\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* trieElement::charset"
array of char 
.PP
Definition at line 9 of file trie\&.h\&.
.SS "void** trieElement::endnode"
array of end node 
.PP
Definition at line 11 of file trie\&.h\&.
.SS "struct \fBtrieElement\fP* trieElement::next"
array of next element 
.PP
Definition at line 10 of file trie\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
