.TH "termMouse_s" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termMouse_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminput\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBc\fP"
.br
.ti -1c
.RI "int \fBbutton\fP"
.br
.ti -1c
.RI "int \fBmeta\fP"
.br
.ti -1c
.RI "int \fBshift\fP"
.br
.ti -1c
.RI "int \fBcontrol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file terminput\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int termMouse_s::button"

.PP
Definition at line 16 of file terminput\&.h\&.
.SS "int termMouse_s::c"

.PP
Definition at line 15 of file terminput\&.h\&.
.SS "int termMouse_s::control"

.PP
Definition at line 19 of file terminput\&.h\&.
.SS "int termMouse_s::meta"

.PP
Definition at line 17 of file terminput\&.h\&.
.SS "int termMouse_s::r"

.PP
Definition at line 14 of file terminput\&.h\&.
.SS "int termMouse_s::shift"

.PP
Definition at line 18 of file terminput\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
