.TH "termRLArea" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termRLArea
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <termreadline\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBcol\fP"
.br
.ti -1c
.RI "int \fBrow\fP"
.br
.ti -1c
.RI "unsigned \fBwidth\fP"
.br
.ti -1c
.RI "unsigned \fBheight\fP"
.br
.ti -1c
.RI "unsigned \fBrowLast\fP"
.br
.ti -1c
.RI "unsigned \fBcolLast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file termreadline\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned termRLArea::col"

.PP
Definition at line 18 of file termreadline\&.h\&.
.SS "unsigned termRLArea::colLast"

.PP
Definition at line 23 of file termreadline\&.h\&.
.SS "unsigned termRLArea::height"

.PP
Definition at line 21 of file termreadline\&.h\&.
.SS "int termRLArea::row"

.PP
Definition at line 19 of file termreadline\&.h\&.
.SS "unsigned termRLArea::rowLast"

.PP
Definition at line 22 of file termreadline\&.h\&.
.SS "unsigned termRLArea::width"

.PP
Definition at line 20 of file termreadline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
