.TH "tvariable" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tvariable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminfo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   long \fBl\fP"
.br
.ti -1c
.RI "   char * \fBs\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file terminfo\&.h\&.
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "long tvariable::l"

.PP
Definition at line 83 of file terminfo\&.h\&.
.SS "char* tvariable::s"

.PP
Definition at line 84 of file terminfo\&.h\&.
.SS "int tvariable::type"

.PP
Definition at line 86 of file terminfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
