.TH "tidbheader" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tidbheader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminfo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBmagic\fP"
.br
.ti -1c
.RI "int16_t \fBnameSize\fP"
.br
.ti -1c
.RI "int16_t \fBbooleanSize\fP"
.br
.ti -1c
.RI "int16_t \fBnumberSize\fP"
.br
.ti -1c
.RI "int16_t \fBoffsetStringCount\fP"
.br
.ti -1c
.RI "int16_t \fBstringTableSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file terminfo\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int16_t tidbheader::booleanSize"

.PP
Definition at line 60 of file terminfo\&.h\&.
.SS "int16_t tidbheader::magic"

.PP
Definition at line 58 of file terminfo\&.h\&.
.SS "int16_t tidbheader::nameSize"

.PP
Definition at line 59 of file terminfo\&.h\&.
.SS "int16_t tidbheader::numberSize"

.PP
Definition at line 61 of file terminfo\&.h\&.
.SS "int16_t tidbheader::offsetStringCount"

.PP
Definition at line 62 of file terminfo\&.h\&.
.SS "int16_t tidbheader::stringTableSize"

.PP
Definition at line 63 of file terminfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
