.TH "termReadLine" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termReadLine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <termreadline\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtermRLArea_s\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBtermRLText_s\fP \fBprompt\fP"
.br
.ti -1c
.RI "\fBtermRLText_s\fP \fBtext\fP"
.br
.ti -1c
.RI "\fButf8Iterator_s\fP \fBit\fP"
.br
.ti -1c
.RI "\fBtermRLCursor_s\fP \fBcursor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file termreadline\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtermRLCursor_s\fP termReadLine::cursor"

.PP
Definition at line 53 of file termreadline\&.h\&.
.SS "\fButf8Iterator_s\fP termReadLine::it"

.PP
Definition at line 52 of file termreadline\&.h\&.
.SS "\fBtermRLArea_s\fP termReadLine::position"

.PP
Definition at line 49 of file termreadline\&.h\&.
.SS "\fBtermRLText_s\fP termReadLine::prompt"

.PP
Definition at line 50 of file termreadline\&.h\&.
.SS "\fBtermRLText_s\fP termReadLine::text"

.PP
Definition at line 51 of file termreadline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
