.TH "tuiListElement" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuiListElement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tuiList\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf8_t\fP * \fBname\fP"
.br
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBc\fP"
.br
.ti -1c
.RI "void * \fBusrdata\fP"
.br
.ti -1c
.RI "\fBtuiEventInt_f\fP \fBonpress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file tuiList\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int tuiListElement::c"

.PP
Definition at line 14 of file tuiList\&.h\&.
.SS "\fButf8_t\fP* tuiListElement::name"

.PP
Definition at line 11 of file tuiList\&.h\&.
.SS "\fBtuiEventInt_f\fP tuiListElement::onpress"

.PP
Definition at line 16 of file tuiList\&.h\&.
.SS "int tuiListElement::r"

.PP
Definition at line 13 of file tuiList\&.h\&.
.SS "void* tuiListElement::usrdata"

.PP
Definition at line 15 of file tuiList\&.h\&.
.SS "int tuiListElement::val"

.PP
Definition at line 12 of file tuiList\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
