.TH "thr" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threads\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_t \fBid\fP"
.br
.ti -1c
.RI "pthread_attr_t \fBattr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 224 of file threads\&.h\&.
.SH "Field Documentation"
.PP 
.SS "pthread_attr_t thr::attr"

.PP
Definition at line 226 of file threads\&.h\&.
.SS "pthread_t thr::id"

.PP
Definition at line 225 of file threads\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
