.TH "tls" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tls
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBhostname\fP"
.br
.ti -1c
.RI "const char * \fBcert\fP"
.br
.ti -1c
.RI "const char * \fBkey\fP"
.br
.ti -1c
.RI "const char * \fBcacert\fP"
.br
.ti -1c
.RI "const char * \fBpassword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file socket\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char* tls::cacert"

.PP
Definition at line 44 of file socket\&.h\&.
.SS "const char* tls::cert"

.PP
Definition at line 42 of file socket\&.h\&.
.SS "const char* tls::hostname"

.PP
Definition at line 41 of file socket\&.h\&.
.SS "const char* tls::key"

.PP
Definition at line 43 of file socket\&.h\&.
.SS "const char* tls::password"

.PP
Definition at line 45 of file socket\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
