.TH "tuiLabel" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuiLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tuiLabel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf8_t\fP * \fBstr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file tuiLabel\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fButf8_t\fP* tuiLabel::str"

.PP
Definition at line 7 of file tuiLabel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
