.TH "termRLText" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termRLText
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <termreadline\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf8_t\fP * \fBstr\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file termreadline\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t termRLText::len"

.PP
Definition at line 28 of file termreadline\&.h\&.
.SS "size_t termRLText::size"

.PP
Definition at line 29 of file termreadline\&.h\&.
.SS "\fButf8_t\fP* termRLText::str"

.PP
Definition at line 27 of file termreadline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
