.TH "tuiButton" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuiButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tuiButton\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf8_t\fP * \fBstr\fP"
.br
.ti -1c
.RI "\fBtuiEventInt_f\fP \fBonpress\fP"
.br
.ti -1c
.RI "void * \fBusrdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file tuiButton\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtuiEventInt_f\fP tuiButton::onpress"

.PP
Definition at line 8 of file tuiButton\&.h\&.
.SS "\fButf8_t\fP* tuiButton::str"

.PP
Definition at line 7 of file tuiButton\&.h\&.
.SS "void* tuiButton::usrdata"

.PP
Definition at line 9 of file tuiButton\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
