.TH "tuiWindow" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuiWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tuiWindow\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBunused\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file tuiWindow\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int tuiWindow::unused"

.PP
Definition at line 7 of file tuiWindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
