.TH "termRLCursor" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termRLCursor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <termreadline\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBrow\fP"
.br
.ti -1c
.RI "unsigned \fBcol\fP"
.br
.ti -1c
.RI "unsigned \fBscrollcol\fP"
.br
.ti -1c
.RI "unsigned \fBscrollrow\fP"
.br
.ti -1c
.RI "unsigned \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file termreadline\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned termRLCursor::col"

.PP
Definition at line 34 of file termreadline\&.h\&.
.SS "unsigned termRLCursor::mode"

.PP
Definition at line 37 of file termreadline\&.h\&.
.SS "unsigned termRLCursor::row"

.PP
Definition at line 33 of file termreadline\&.h\&.
.SS "unsigned termRLCursor::scrollcol"

.PP
Definition at line 35 of file termreadline\&.h\&.
.SS "unsigned termRLCursor::scrollrow"

.PP
Definition at line 36 of file termreadline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
