.TH "trie" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trie
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trie\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtrieElement_s\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBtrieFree_f\fP \fBfree\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file trie\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtrieFree_f\fP trie::free"
< callback free function 
.PP
Definition at line 16 of file trie\&.h\&.
.SS "\fBtrieElement_s\fP trie::root"
< root 
.PP
Definition at line 15 of file trie\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
