.TH "tidbextend" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tidbextend
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminfo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBbooleanSize\fP"
.br
.ti -1c
.RI "int16_t \fBnumberSize\fP"
.br
.ti -1c
.RI "int16_t \fBstringCount\fP"
.br
.ti -1c
.RI "int16_t \fBstringTableSize\fP"
.br
.ti -1c
.RI "int16_t \fBlastoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file terminfo\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int16_t tidbextend::booleanSize"

.PP
Definition at line 67 of file terminfo\&.h\&.
.SS "int16_t tidbextend::lastoffset"

.PP
Definition at line 71 of file terminfo\&.h\&.
.SS "int16_t tidbextend::numberSize"

.PP
Definition at line 68 of file terminfo\&.h\&.
.SS "int16_t tidbextend::stringCount"

.PP
Definition at line 69 of file terminfo\&.h\&.
.SS "int16_t tidbextend::stringTableSize"

.PP
Definition at line 70 of file terminfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
