.TH "utf8Iterator" 3 "Thu Apr 2 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utf8Iterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utf8\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fButf8_t\fP * \fBbegin\fP"
.br
.ti -1c
.RI "\fButf8_t\fP * \fBstr\fP"
.br
.ti -1c
.RI "size_t \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
obj iterator 
.PP
Definition at line 40 of file utf8\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fButf8_t\fP* utf8Iterator::begin"
begin of string 
.PP
Definition at line 41 of file utf8\&.h\&.
.SS "size_t utf8Iterator::id"
index 
.PP
Definition at line 43 of file utf8\&.h\&.
.SS "\fButf8_t\fP* utf8Iterator::str"
cursor string 
.PP
Definition at line 42 of file utf8\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
