.TH "valign" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
valign
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vectorization\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBpre\fP"
.br
.ti -1c
.RI "size_t \fBaligned\fP"
.br
.ti -1c
.RI "size_t \fBpost\fP"
.br
.ti -1c
.RI "size_t \fBstart\fP"
.br
.ti -1c
.RI "size_t \fBend\fP"
.br
.ti -1c
.RI "void * \fBscalarpre\fP"
.br
.ti -1c
.RI "void * \fBscalarpost\fP"
.br
.ti -1c
.RI "void * \fBvector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file vectorization\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t valign::aligned"

.PP
Definition at line 8 of file vectorization\&.h\&.
.SS "size_t valign::end"

.PP
Definition at line 11 of file vectorization\&.h\&.
.SS "size_t valign::post"

.PP
Definition at line 9 of file vectorization\&.h\&.
.SS "size_t valign::pre"

.PP
Definition at line 7 of file vectorization\&.h\&.
.SS "void* valign::scalarpost"

.PP
Definition at line 13 of file vectorization\&.h\&.
.SS "void* valign::scalarpre"

.PP
Definition at line 12 of file vectorization\&.h\&.
.SS "size_t valign::start"

.PP
Definition at line 10 of file vectorization\&.h\&.
.SS "void* valign::vector"

.PP
Definition at line 14 of file vectorization\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
