.TH "vector" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vector\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBminimal\fP"
.br
.ti -1c
.RI "size_t \fBsof\fP"
.br
.ti -1c
.RI "void * \fBelement\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file vector\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t vector::count"
used object 
.PP
Definition at line 9 of file vector\&.h\&.
.SS "void* vector::element[0]"
pointer to mem 
.PP
Definition at line 12 of file vector\&.h\&.
.SS "size_t vector::minimal"
minimal element to allocate 
.PP
Definition at line 10 of file vector\&.h\&.
.SS "size_t vector::size"
size of allocated mem 
.PP
Definition at line 8 of file vector\&.h\&.
.SS "size_t vector::sof"
sizeof type 
.PP
Definition at line 11 of file vector\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
