.TH "wwwBuffer_s" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wwwBuffer_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <www\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.ti -1c
.RI "size_t \fBupto\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file www\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* wwwBuffer_s::buf"

.PP
Definition at line 34 of file www\&.h\&.
.SS "size_t wwwBuffer_s::len"

.PP
Definition at line 36 of file www\&.h\&.
.SS "size_t wwwBuffer_s::offset"

.PP
Definition at line 37 of file www\&.h\&.
.SS "size_t wwwBuffer_s::size"

.PP
Definition at line 35 of file www\&.h\&.
.SS "size_t wwwBuffer_s::upto"

.PP
Definition at line 38 of file www\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
