.TH "www" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
www
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <www\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "CURL * \fBh\fP"
.br
.ti -1c
.RI "\fBwwwBuffer_s\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBwwwBuffer_s\fP \fBbody\fP"
.br
.ti -1c
.RI "struct curl_slist * \fBhlist\fP"
.br
.ti -1c
.RI "char * \fBcustomRQ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file www\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBwwwBuffer_s\fP www::body"

.PP
Definition at line 70 of file www\&.h\&.
.SS "char* www::customRQ"

.PP
Definition at line 72 of file www\&.h\&.
.SS "CURL* www::h"

.PP
Definition at line 68 of file www\&.h\&.
.SS "\fBwwwBuffer_s\fP www::header"

.PP
Definition at line 69 of file www\&.h\&.
.SS "struct curl_slist* www::hlist"

.PP
Definition at line 71 of file www\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
