.TH "xorgProperty" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgProperty
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xcb_atom_t \fBatom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 323 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "xcb_atom_t xorgProperty::atom"

.PP
Definition at line 324 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
