.TH "xorgClipboard" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgClipboard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBeventPaste\fP"
.br
.ti -1c
.RI "xcb_window_t \fBrequestor\fP"
.br
.ti -1c
.RI "xcb_atom_t \fBproperty\fP"
.br
.ti -1c
.RI "xcb_atom_t \fBtype\fP"
.br
.ti -1c
.RI "int \fBprimary\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 341 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* xorgClipboard::data"

.PP
Definition at line 347 of file xorg\&.h\&.
.SS "int xorgClipboard::eventPaste"

.PP
Definition at line 342 of file xorg\&.h\&.
.SS "int xorgClipboard::primary"

.PP
Definition at line 346 of file xorg\&.h\&.
.SS "xcb_atom_t xorgClipboard::property"

.PP
Definition at line 344 of file xorg\&.h\&.
.SS "xcb_window_t xorgClipboard::requestor"

.PP
Definition at line 343 of file xorg\&.h\&.
.SS "size_t xorgClipboard::size"

.PP
Definition at line 348 of file xorg\&.h\&.
.SS "xcb_atom_t xorgClipboard::type"

.PP
Definition at line 345 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
