.TH "xorgWindow" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xcb_window_t \fBidxcb\fP"
.br
.ti -1c
.RI "char * \fBclass\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBnetname\fP"
.br
.ti -1c
.RI "char * \fBtitle\fP"
.br
.ti -1c
.RI "xcb_icccm_wm_hints_t \fBhints\fP"
.br
.ti -1c
.RI "xcb_size_hints_t \fBsize\fP"
.br
.ti -1c
.RI "unsigned \fBx\fP"
.br
.ti -1c
.RI "unsigned \fBy\fP"
.br
.ti -1c
.RI "unsigned \fBw\fP"
.br
.ti -1c
.RI "unsigned \fBh\fP"
.br
.ti -1c
.RI "unsigned \fBborder\fP"
.br
.ti -1c
.RI "unsigned \fBvisible\fP"
.br
.ti -1c
.RI "unsigned \fBdesktop\fP"
.br
.ti -1c
.RI "xcb_atom_t * \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBtypeCount\fP"
.br
.ti -1c
.RI "xcb_atom_t * \fBstate\fP"
.br
.ti -1c
.RI "size_t \fBstateCount\fP"
.br
.ti -1c
.RI "\fBxorgWindowStrut_s\fP \fBstrut\fP"
.br
.ti -1c
.RI "\fBxorgWindowStrutPartial_s\fP \fBpartial\fP"
.br
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 214 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned xorgWindow::border"

.PP
Definition at line 222 of file xorg\&.h\&.
.SS "char* xorgWindow::class"

.PP
Definition at line 216 of file xorg\&.h\&.
.SS "unsigned xorgWindow::desktop"

.PP
Definition at line 223 of file xorg\&.h\&.
.SS "unsigned xorgWindow::h"

.PP
Definition at line 222 of file xorg\&.h\&.
.SS "xcb_icccm_wm_hints_t xorgWindow::hints"

.PP
Definition at line 220 of file xorg\&.h\&.
.SS "xcb_window_t xorgWindow::idxcb"

.PP
Definition at line 215 of file xorg\&.h\&.
.SS "char* xorgWindow::name"

.PP
Definition at line 217 of file xorg\&.h\&.
.SS "char* xorgWindow::netname"

.PP
Definition at line 218 of file xorg\&.h\&.
.SS "\fBxorgWindowStrutPartial_s\fP xorgWindow::partial"

.PP
Definition at line 229 of file xorg\&.h\&.
.SS "pid_t xorgWindow::pid"

.PP
Definition at line 230 of file xorg\&.h\&.
.SS "xcb_size_hints_t xorgWindow::size"

.PP
Definition at line 221 of file xorg\&.h\&.
.SS "xcb_atom_t* xorgWindow::state"

.PP
Definition at line 226 of file xorg\&.h\&.
.SS "size_t xorgWindow::stateCount"

.PP
Definition at line 227 of file xorg\&.h\&.
.SS "\fBxorgWindowStrut_s\fP xorgWindow::strut"

.PP
Definition at line 228 of file xorg\&.h\&.
.SS "char* xorgWindow::title"

.PP
Definition at line 219 of file xorg\&.h\&.
.SS "xcb_atom_t* xorgWindow::type"

.PP
Definition at line 224 of file xorg\&.h\&.
.SS "size_t xorgWindow::typeCount"

.PP
Definition at line 225 of file xorg\&.h\&.
.SS "unsigned xorgWindow::visible"

.PP
Definition at line 222 of file xorg\&.h\&.
.SS "unsigned xorgWindow::w"

.PP
Definition at line 222 of file xorg\&.h\&.
.SS "unsigned xorgWindow::x"

.PP
Definition at line 222 of file xorg\&.h\&.
.SS "unsigned xorgWindow::y"

.PP
Definition at line 222 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
