.TH "xorgWindowStrut" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgWindowStrut
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBleft\fP"
.br
.ti -1c
.RI "unsigned \fBright\fP"
.br
.ti -1c
.RI "unsigned \fBtop\fP"
.br
.ti -1c
.RI "unsigned \fBbottom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 193 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned xorgWindowStrut::bottom"

.PP
Definition at line 194 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrut::left"

.PP
Definition at line 194 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrut::right"

.PP
Definition at line 194 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrut::top"

.PP
Definition at line 194 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
