.TH "xorgSurface" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgSurface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xcb_gcontext_t \fBgc\fP"
.br
.ti -1c
.RI "xcb_image_t * \fBximage\fP"
.br
.ti -1c
.RI "\fBg2dImage_s\fP * \fBimg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "xcb_gcontext_t xorgSurface::gc"

.PP
Definition at line 150 of file xorg\&.h\&.
.SS "\fBg2dImage_s\fP* xorgSurface::img"

.PP
Definition at line 152 of file xorg\&.h\&.
.SS "xcb_image_t* xorgSurface::ximage"

.PP
Definition at line 151 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
