.TH "xorgMove" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgMove
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "unsigned \fBw\fP"
.br
.ti -1c
.RI "unsigned \fBh\fP"
.br
.ti -1c
.RI "unsigned \fBborder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 292 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned xorgMove::border"

.PP
Definition at line 297 of file xorg\&.h\&.
.SS "unsigned xorgMove::h"

.PP
Definition at line 296 of file xorg\&.h\&.
.SS "unsigned xorgMove::w"

.PP
Definition at line 295 of file xorg\&.h\&.
.SS "int xorgMove::x"

.PP
Definition at line 293 of file xorg\&.h\&.
.SS "int xorgMove::y"

.PP
Definition at line 294 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
