.TH "xorgClipboard" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgClipboard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBeventPaste\fP"
.br
.ti -1c
.RI "xcb_window_t \fBrequestor\fP"
.br
.ti -1c
.RI "xcb_atom_t \fBproperty\fP"
.br
.ti -1c
.RI "xcb_atom_t \fBtype\fP"
.br
.ti -1c
.RI "int \fBprimary\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 333 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* xorgClipboard::data"

.PP
Definition at line 339 of file xorg\&.h\&.
.SS "int xorgClipboard::eventPaste"

.PP
Definition at line 334 of file xorg\&.h\&.
.SS "int xorgClipboard::primary"

.PP
Definition at line 338 of file xorg\&.h\&.
.SS "xcb_atom_t xorgClipboard::property"

.PP
Definition at line 336 of file xorg\&.h\&.
.SS "xcb_window_t xorgClipboard::requestor"

.PP
Definition at line 335 of file xorg\&.h\&.
.SS "size_t xorgClipboard::size"

.PP
Definition at line 340 of file xorg\&.h\&.
.SS "xcb_atom_t xorgClipboard::type"

.PP
Definition at line 337 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
