.TH "xorgUserData" 3 "Fri May 15 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgUserData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "void * \fBrequest\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 351 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* xorgUserData::data"

.PP
Definition at line 354 of file xorg\&.h\&.
.SS "void* xorgUserData::request"

.PP
Definition at line 353 of file xorg\&.h\&.
.SS "size_t xorgUserData::size"

.PP
Definition at line 355 of file xorg\&.h\&.
.SS "int xorgUserData::type"

.PP
Definition at line 352 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
