.TH "xorgKeyboard" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgKeyboard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBxorgKey_e\fP \fBevent\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBabsolute\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBrelative\fP"
.br
.ti -1c
.RI "unsigned \fBbutton\fP"
.br
.ti -1c
.RI "unsigned \fBmodifier\fP"
.br
.ti -1c
.RI "unsigned long \fBkeycode\fP"
.br
.ti -1c
.RI "unsigned long \fBkeysym\fP"
.br
.ti -1c
.RI "\fButf8_t\fP \fButf8\fP [\fBXKB_UTF_MAX\fP]"
.br
.ti -1c
.RI "\fButf_t\fP \fButf\fP"
.br
.ti -1c
.RI "long \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 279 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBg2dPoint_s\fP xorgKeyboard::absolute"

.PP
Definition at line 281 of file xorg\&.h\&.
.SS "unsigned xorgKeyboard::button"

.PP
Definition at line 283 of file xorg\&.h\&.
.SS "\fBxorgKey_e\fP xorgKeyboard::event"

.PP
Definition at line 280 of file xorg\&.h\&.
.SS "unsigned long xorgKeyboard::keycode"

.PP
Definition at line 285 of file xorg\&.h\&.
.SS "unsigned long xorgKeyboard::keysym"

.PP
Definition at line 286 of file xorg\&.h\&.
.SS "unsigned xorgKeyboard::modifier"

.PP
Definition at line 284 of file xorg\&.h\&.
.SS "\fBg2dPoint_s\fP xorgKeyboard::relative"

.PP
Definition at line 282 of file xorg\&.h\&.
.SS "long xorgKeyboard::time"

.PP
Definition at line 289 of file xorg\&.h\&.
.SS "\fButf_t\fP xorgKeyboard::utf"

.PP
Definition at line 288 of file xorg\&.h\&.
.SS "\fButf8_t\fP xorgKeyboard::utf8[\fBXKB_UTF_MAX\fP]"

.PP
Definition at line 287 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
