.TH "xorgWindowStrutPartial" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgWindowStrutPartial
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBleft\fP"
.br
.ti -1c
.RI "unsigned \fBright\fP"
.br
.ti -1c
.RI "unsigned \fBtop\fP"
.br
.ti -1c
.RI "unsigned \fBbottom\fP"
.br
.ti -1c
.RI "unsigned \fBleft_start_y\fP"
.br
.ti -1c
.RI "unsigned \fBleft_end_y\fP"
.br
.ti -1c
.RI "unsigned \fBright_start_y\fP"
.br
.ti -1c
.RI "unsigned \fBright_end_y\fP"
.br
.ti -1c
.RI "unsigned \fBtop_start_x\fP"
.br
.ti -1c
.RI "unsigned \fBtop_end_x\fP"
.br
.ti -1c
.RI "unsigned \fBbottom_start_x\fP"
.br
.ti -1c
.RI "unsigned \fBbottom_end_x\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 198 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned xorgWindowStrutPartial::bottom"

.PP
Definition at line 199 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::bottom_end_x"

.PP
Definition at line 203 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::bottom_start_x"

.PP
Definition at line 203 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::left"

.PP
Definition at line 199 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::left_end_y"

.PP
Definition at line 200 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::left_start_y"

.PP
Definition at line 200 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::right"

.PP
Definition at line 199 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::right_end_y"

.PP
Definition at line 201 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::right_start_y"

.PP
Definition at line 201 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::top"

.PP
Definition at line 199 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::top_end_x"

.PP
Definition at line 202 of file xorg\&.h\&.
.SS "unsigned xorgWindowStrutPartial::top_start_x"

.PP
Definition at line 202 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
