.TH "xorgClient" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgClient
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xcb_atom_t \fBtype\fP"
.br
.ti -1c
.RI "uint8_t \fBformat\fP"
.br
.ti -1c
.RI "uint8_t \fBdata\fP [20]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 327 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t xorgClient::data[20]"

.PP
Definition at line 330 of file xorg\&.h\&.
.SS "uint8_t xorgClient::format"

.PP
Definition at line 329 of file xorg\&.h\&.
.SS "xcb_atom_t xorgClient::type"

.PP
Definition at line 328 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
