.TH "xorgMouse" 3 "Fri Apr 24 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgMouse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBxorgMouse_e\fP \fBevent\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBabsolute\fP"
.br
.ti -1c
.RI "\fBg2dPoint_s\fP \fBrelative\fP"
.br
.ti -1c
.RI "unsigned \fBbutton\fP"
.br
.ti -1c
.RI "unsigned \fBkey\fP"
.br
.ti -1c
.RI "long \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 250 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBg2dPoint_s\fP xorgMouse::absolute"

.PP
Definition at line 252 of file xorg\&.h\&.
.SS "unsigned xorgMouse::button"

.PP
Definition at line 254 of file xorg\&.h\&.
.SS "\fBxorgMouse_e\fP xorgMouse::event"

.PP
Definition at line 251 of file xorg\&.h\&.
.SS "unsigned xorgMouse::key"

.PP
Definition at line 255 of file xorg\&.h\&.
.SS "\fBg2dPoint_s\fP xorgMouse::relative"

.PP
Definition at line 253 of file xorg\&.h\&.
.SS "long xorgMouse::time"

.PP
Definition at line 256 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
