.TH "xorgFocus" 3 "Thu Apr 23 2020" "Version 0.4.5" "Easy Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xorgFocus
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xorg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoutin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 315 of file xorg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int xorgFocus::outin"

.PP
Definition at line 316 of file xorg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Easy Framework from the source code\&.
